### ISSUE TITLE
add a visual band scanner to SCANsat

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#10]
- (**Nertea**) suggests that we add a visual band scanner (ie, a optical telescope?)
- I think this is similar to functionality that ISA MapSat once had, but I can't be sure (never got it to work). Anyone know?
- S/he also suggests that maybe this should be a rendering of the planet texture overlaid with a greyscale elevation map
- and that this should only work when the satellite is on the day side of the day/night terminator.

**Comment by Ruedii** [comment]
Yeah, I agree with this one being a good thing to add.

Another thing is to have the lesser version do only grayscale and/or lower resolution.  The higher resolution version could even require multiple passes to get a high quality scan.

**Comment by reytiger** [comment]
Or the higher resolution could be a toggleable mode on the scanner, having a narrower field of view, thereby requiring a bit more work to get 100%

**Comment by Ruedii** [comment]
Yes and the early tech tree low-res only part (called "surface
reflectivity") should also only do greyscale and have a very low resolution
(similar resolution to the low resolution RADAR altitude scanner).  It
should also have a very wide FOV compared to the color visual band scanner
available later.

The high res part should have two modes, low-res and high res.  Both should
be color and the high res should have a narrower FOV.

This allows the player to scan three times, getting science and a sense of
progress each time.

Additionally, this will allow for more contracts if contract integration is
added (this is on the may be done eventually list if I recall, may require
Fine Print, if Fine Print adds external mod hooks using mod config files).

**Comment by FalcoGer** [comment]
I think this can be closed.

**Comment by DMagic1** [comment]
Added in version 20.
