### ISSUE TITLE
PLS Add Uraninite and Karborundum to scanner definition.

### ISSUE THREAD

**Issue by Funkstex** [KSPModStewards/SCANsat#104]
They are both not showable in Big Map because as far as I understand they aren't defined as scantypes.

**Comment by DMagic1** [comment]
Karborundum is not shown by design, but Uraninite just needs a name change. I'm also wondering about the other resources.

**Comment by Funkstex** [comment]
Is it done, if I change the resource name in in scantypes[Uranium -->Uraninite]?, I think they are hardcoded in source... In what way wondering? about the unused ones?  I know Karborundum isn't shown because it's hard to find, but if you've find it once it would be nice to see on the map where it was. In general, shouldn't it be leaved to the scanner part which resource is scanned in what environment.

**Comment by DMagic1** [comment]
Is it changed already do you mean? No. Pushing new releases for a small fix like this isn't going to happen.

You should only need to change the resource name in the "SCANResource.cfg" file found in the SCANsat/Resources folder. Just change the name from Uranium to Uraninite. It should work, but I won't get around to actually testing it for a while. Nothing needs to be changed in code to make this work.

This will only work in the dev release, version 9.4.1.
