### ISSUE TITLE
SCANSat crash at space center

### ISSUE THREAD

**Issue by Czar59** [KSPModStewards/SCANsat#109]
Hello! Im relatively new to KSP but have been playing essentially non-stop since i purchased it. My KSP is already heavily modded but when i discovered SCANSat i absolutely had to get it. So far this is the only mod who's issues i havent been able to figure out. I play on 64 bit and everything loads just fine until i click on my career mode save and it crashes trying to load the space center. Is it just not compatible with 64 bit? Im dying to experience this amazing mod please help!
Also, im sorry but idk hot to attach text files so idk how to attach my output log

Edit: I think i figured the outputlog out. : https://gist.github.com/Czar59/6e12f5e9ef9c773a587e

**Comment by DMagic1** [comment]
The only error I see is from a clouds addon: 

```
NullReferenceException: Object reference not set to an instance of an object
at Clouds.Clouds.Update () [0x00000] in <filename unknown>:0 
```

And the actual crash occurs just after clouds is doing something:

```
Clouds: Volume Initialized
Clouds: Volume Initialized
Clouds: Volume Initialized
Clouds: Volume Initialized
Crash!!!
```

The stack trace at the end is pointing to something else: 

```
========== OUTPUTING STACK TRACE ==================
(0x0000000103950000) ((module-name not available)): (filename not available): (function-name     not available) + 0x0
(0x000000007BF9EF39) (Mono JIT code): (filename not available): ApplicationLauncher:OnSceneLoaded (GameScenes) + 0x279 (000000007BF9ECC00000000007BF9EFC4) [0000000003904D48 - Unity Root Domain] + 0x0
(0x000000007BEB0635) (Mono JIT code): (filename not available):  EventData`1<GameScenes>:Fire (GameScenes) + 0x145 (000000007BEB04F0 000000007BEB0815) [0000000003904D48 - Unity Root Domain] + 0x0
(0x000000001B875F27) (Mono JIT code): (filename not available):  HighLogic/:MoveNext () + 0x77 (000000001B875EB0 000000001B875F41) [0000000003904D48 - Unity Root Domain] + 0x0
(0x000000000422919B) (Mono JIT code): (filename not available):  (wrapper runtime-invoke) <Module>:runtime_invoke_bool__this__ (object,intptr,intptr,intptr) + 0x6b (0000000004229130 000000000422922C) [0000000003904D48 - Unity Root Domain] + 0x0
(0x00007FFA9A433A82) (mono): (filename not available): mono_set_defaults + 0x2b9e
(0x00000000B26AB780) ((module-name not available)): (filename not available): (function-name not available) + 0x0
(0x00000000FFFFFFFF) ((module-name not available)): (filename not available): (function-name not available) + 0x0
(0x0000000003904D48) ((module-name not available)): (filename not available): (function-name not available) + 0x0
========== END OF STACKTRACE ===========
**** Crash! ****
```

64bit KSP is notoriously unstable, and crashes might occur for a number of different reasons. That it may be stable without a certain addon doesn't mean that this addon is actually causing a problem, just that 64bit KSP is very unstable on Windows.

**Comment by Czar59** [comment]
I cannot express how much i appreciate the speed at which you responded thank you! I thought it was something with SCANsat because when i remove the mod everything loads fine; clouds included. I will try it without the clouds now and let you know if that helps. BTW i love Orbital Science.

In additon i know 64 is very unstable i just have too many mods for regular 32 bit, and im a mod addict lol

**Comment by Czar59** [comment]
Its working!
