### ISSUE TITLE
Add Uraninite as a SCANsat resource

### ISSUE THREAD

**Issue by Olympic1** [KSPModStewards/SCANsat#111]
Can you add Uraninite into [SCANresource.cfg](https://github.com/S-C-A-N/SCANsat/blob/dev/SCANassets/Resources/SCANresource.cfg)? Or are resources automatically defined with a SCANtype number. If so, how can I find this number and add it to a sensor.

```
SCANSAT_SENSOR
{
    name = Uraninite
    SCANtype = 524288 //2^19  <-- Is this available
    ColorEmpty = 0.1858824, 0.3105883, 0.1929412
    ColorFull = 0.08235294, 0.6901961, 0.1019608
}
```

**Comment by DMagic1** [comment]
I don't see any reason to leave Uranium around, so I just switched out the name; 9416439b09ad52e6f94c963c93ddc1b680738891

Is there some KSPI to Regolith support available that uses Uranium? That's the only reason I can think of for having both.
