### ISSUE TITLE
Karbonite/OSRX problem

### ISSUE THREAD

**Issue by Stikkychaos** [KSPModStewards/SCANsat#114]
Well, despite having both Karbonite and scansat updated, i cannot see any resources on the map.
Screens were done after reinstalling scansat 8.1 and wiping all scansat data, but it changed nothing.
![screenshot_2](https://cloud.githubusercontent.com/assets/10728602/5924341/492d4a16-a65b-11e4-928c-921056db6f47.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/10728602/5924342/4932d17a-a65b-11e4-9de7-3f9a3bcdaf05.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/10728602/5924343/49378508-a65b-11e4-91b1-42daab451a05.png)

**Comment by JoeClacks** [comment]
You need to have v9.0 rc4 or greater installed for Karbonite resources to work

**Comment by DMagic1** [comment]
Always check the first post of the SCANsat thread for news about updates and features. Use the [dev version](http://forum.kerbalspaceprogram.com/threads/96859) for resource scanning.

**Comment by Stikkychaos** [comment]
thank a bunch :D
