### ISSUE TITLE
More color variance for resource concentrations.

### ISSUE THREAD

**Issue by enceos** [KSPModStewards/SCANsat#117]
The current resource overlay is very dim and with little to no gradient. It's impossible to find hotspots of resources visually on the map. To find the best concentration of a resource I have to swing my cursor back and forth watching the percentages change. Is it possible to make the resource overlay color intensity more dependent on the percentage of resource concentration? It would be nice if we could change the percentage sensitivity and top and bottom color ourselves in the settings menu (set the floor and ceiling percentage numbers and their colors). For example, floor and ceiling 3% and 7%, yellow and blue colors respectively. The map needs to go into black & white mode automatically when resource overlay is applied, thus players will be able to find the highest  resource concentrations visually with no mouse hovering effort.

**Comment by DMagic1** [comment]
What I've been thinking is to extend the color management window to include biome maps and resources. 

I'm thinking that I could provide two color wheels to select the end points, or some other type of color selector and a transparency slider. Sliders to select the end point concentrations would help too. Each resource could have its own colors and settings defined and saved.

I'll also add something similar for biome maps, along with an option to switch to the stock biome map textures.

**Comment by enceos** [comment]
Awesome!
