### ISSUE TITLE
No Monitoring Map, Start Scan Buttons dont work, No Toolbar!

### ISSUE THREAD

**Issue by Jagdfrettchen** [KSPModStewards/SCANsat#119]
Hey there, i have the following Issues.
If i try to scan, the startbutton of my scanners are jumping back to "start" after i clicket em, so i cant abbort scanning because it never begins.
I cant open a Map or Big Map, because i do not have a button for it, but on the last version i had a button but it didnt work.
i have no toolbar in the corners of my screen.

i use version 10.0 but the previous version had nealy the same issues, both versions dont work with me!

i cant upload a logfile because this site says to me "Unfortunately, we don't support that file type. "
and it is bigger as 10 MB it has about 34 MB. but if you realy need i can try on another time to ut it into dropbox.

i just can give you some informations about my system and my mods i have. please help me!
i cant search for ressources or something.. and i have mission to colonize the mun!
i play career mode.
and yes i tryed more as 1 time to reinstall the mod, and repaired my game via Steam.

here some informations->

Copy the first lines of the Log file:

Initialize engine version: 4.5.5f1 (7684ad0c5a44)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 9.0c [nvd3dum.dll 9.18.13.4475]
    Renderer: NVIDIA GeForce GTX 770
    Vendor:   NVIDIA
    VRAM:     1985 MB (via DXGI)
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=0 INTZ=1 RAWZ=0 NULL=1 RESZ=0 SlowINTZ=0

My Modlist:

BetterRoveMates
TinkerGnomeToys
slimMonopropellant
Gerdin_atmospherics
PMV-25
PMV-50
HooliganLabs
NearFutureSolar
TreeLoader
KSP Deutsch Patch
ShipManifest
TarsierSpaceTech
JSI
NearFutureProps
NearFutureSpacecraft
ModRocketSys
NearFutureElectrical
NearFutureConstruction
CollisionFX
Romfarer
CrossFeedEnabler
NearFuturePropulsion
SpaceY-Lifters
DMagic Orbital Science
Chatterer
MechJeb2
KAS
StationScience
000_USITools
CommunityResourcePack
Regolith
KAX
Firespitter
SCANsat
ActiveTextureManagement
modulercsfx
Part for Marce
Part for Sirkut
Part for Wave
UmbraSpaceIndustries ->

```
AMT
exppack
EZSnack
FTT
karbonite
karboniteplus
Kolonization
soundingrockets
srvpack
warpdrive 
```

ThunderAerospace ->

```
TacLifeSupport
TacLifeSupportContainers
TacLifeSupportHexCans
TacLifeSupportMFT
TacLifeSupportRecyclers 
```

ModuleManager.2.5.9

Hope you can help me, thank you allready.

**Comment by DMagic1** [comment]
Tarsier Space Tech is broken. Delete it.

**Comment by Jagdfrettchen** [comment]
ill try it out and give you a review, thanks
