### ISSUE TITLE
No resources button

### ISSUE THREAD

**Issue by ChlepzKielbasom** [KSPModStewards/SCANsat#120]
Hello, I am missing resources button when opening map.

Gamedata folder
![mods](https://cloud.githubusercontent.com/assets/10964983/6154756/685bcc08-b22e-11e4-800b-003e5513ba31.png)

Output log

https://www.dropbox.com/s/yp80hz6vrelmb0u/output_log.txt?dl=0

**Comment by DMagic1** [comment]
It looks like the version of Regolith you have is outdated. I think the [latest version of Karbonite](https://github.com/BobPalmer/Karbonite/releases/tag/0.5.5) should have the updated version, just make sure you install that last, and don't overwrite the newer version of Regolith with an older version.

**Comment by Retrograde115** [comment]
I had the same problem. The latest Regolith version is 1.7.0, while the latest Karbonite release includes Regolith version 1.5.0. You have to downgrade Regolith to 1.5.0 in order for the resource button to work. (Also, neither Regolith version works with the latest SCANsat pre-releases, make sure you're using the standard release.)

**Comment by DMagic1** [comment]
No, you should be using the latest version of Regolith, 1.7. The supported addons shown on the Readme aren't always up to date; 1.7 is working just fine with SCANsat.

And as the dates and version numbers suggest, the pre-release versions are very old and not supported.

**Comment by Retrograde115** [comment]
Sorry, I posted this at 3am last night and didn't realize how old the pre-releases are, I thought they were new. Sorry for any confusion my late night self caused.
