### ISSUE TITLE
Scansat scans without scanners on upper stages

### ISSUE THREAD

**Issue by futrtrubl** [KSPModStewards/SCANsat#122]
If a vessel with active scanners on a lower stage stages, the upper stage is the one that thinks it has scanners and scans. The lower stage with the scanners does nothing. Persists through scene changes and restarts.
Corrections: The lower stage that actually has the scanners will start scanning if the scanners are reactivated (they deactivated upon staging). Upper stage continues scanning.
![scansat_bug](https://cloud.githubusercontent.com/assets/5351740/6385743/85925652-bd3c-11e4-985d-ab3f8027d482.jpg)

**Comment by DMagic1** [comment]
Thanks for logging this as an issue. This is something I keep noticing then forgetting about...

Whichever vessel keeps the original Vessel.ID continues to be registered as a SCANsat vessel. There's no way to unregister it without the parts, so it stays that way.

It should be a relatively simple fix, just watch for when new vessels are created (either by undocking or decoupling, it's the same GameEvent), check for the presence of scanners, and update the vessel dictionary accordingly.
