### ISSUE TITLE
Regolith handles atmospheric and interstellar resources too; it would be nice to be able to scan for them

### ISSUE THREAD

**Issue by dak180** [KSPModStewards/SCANsat#124]
Especially the interstellar resources; space is big and randomly generated bands could be anywhere.

**Comment by DMagic1** [comment]
I'm not sure how this would be accomplished or displayed.

My understanding is that atmospheric and interplanetary resources vary by altitude. SCANsat has no way to take altitude into consideration when generating its scanning coverage maps (and doing so would drastically increase the size and complexity of those coverage maps) and I don't know how such a thing would be displayed over a 2D map anyway.

**Comment by dak180** [comment]
My suggestion would be to do something like what the map resource overlay does except with clouds that sit in space for interplanetary resources. I am less sure about the best way to do things for atmospheric resources though that may just be as a result of not being entirely sure what exactly Regolith does as far their placement.

**Comment by futrtrubl** [comment]
There is no lat/long variance of atmospheric/exospheric resources. Exospheric resource concentration only changes with altitude with a peak altitude (there was a bug where it varied with biome but that should be fixed), while atmospheric resource relative abundance doesn't vary at all, absolute concentration is directly proportional to atmospheric density.
So there are no clouds that sit in space.
