### ISSUE TITLE
can't transmit science points even when there are multiple antennas on board

### ISSUE THREAD

**Issue by repkid** [KSPModStewards/SCANsat#137]
I have ksp 1.02 with SCANsat v12.0 and when I try to send data back to kerbin it either says there aren't any antennas on board or it starts to transmit but no science is sent.

**Comment by DMagic1** [comment]
Do you have Science Alert installed. Update it to the latest version, this is a known problem fixed in that version.

**Comment by repkid** [comment]
thanks for the quick reply!

**Comment by futrtrubl** [comment]
repkid, did that fix it? if so then DMagic or yourself can close the issue.
