### ISSUE TITLE
Settings for Stock Toolbar is not saved.

### ISSUE THREAD

**Issue by RealKolago** [KSPModStewards/SCANsat#138]
Setting for Stock Toolbar "Off" goes back "On" after restarting the game.

**Comment by DMagic1** [comment]
It should be persistent. It won't save the setting across different save files, but for any given save it should stay as you've selected. 

Are there any other problems, I don't see how this could be happening without lots of other issues.

**Comment by RealKolago** [comment]
Ok, I see the problem. I did test flights and revert the flights... so it was restored as before the flight.

**Comment by RealKolago** [comment]
Close
