### ISSUE TITLE
Parts not in tech tree

### ISSUE THREAD

**Issue by Anonymous13000** [KSPModStewards/SCANsat#142]
I think I must have installed scansat incorrectly because i have it in the GameData folder of KSP 1.0.2 and the scansat specific parts don't show up in the tech tree. They're just not there. Any clues?

**Comment by Anonymous13000** [comment]
Small update I checked in the partdatabase.cfg and the parts were never transferred to there

**Comment by DMagic1** [comment]
Can you get me the log files, or check if the line [SCANlogger]... shows up anywhere, it should come up  when you get to the main menu.

**Comment by Anonymous13000** [comment]
I reinstalled all of them again and the parts show up. Don't really know what I did differently.

**Comment by Anonymous13000** [comment]
Sorry didn't copy the log files from before. All I saw was that the parts weren't in the parts config file for ksp itself
