### ISSUE TITLE
NullReferenceException in SCANuiUtil.drawLabel [Bug]

### ISSUE THREAD

**Issue by ThenTech** [KSPModStewards/SCANsat#148]
There is a NullReferenceException being thrown when trying to view the detailed map.

Starts with:

```
[Toolbar] [ERROR] button texture not found: SCANsat/Icons/SCANsat_Icon
```

Callstack:

``` java
NullReferenceException: Object reference not set to an instance of an object
    SCANsat.SCAN_UI.UI_Framework.SCANuiUtil.drawLabel (Rect r, System.String txt, Boolean Flash, Boolean aligned, Boolean outline)
    SCANsat.SCAN_UI.UI_Framework.SCANuiUtil.drawVesselLabel (Rect maprect, SCANsat.SCAN_Map.SCANmap map, Int32 num, .Vessel vessel)
    SCANsat.SCAN_UI.SCANmainMap.vesselInfo (.Vessel scanV, Rect r, Int32 i, Boolean b)
    SCANsat.SCAN_UI.SCANmainMap.vesselInfo (Int32 id)
    SCANsat.SCAN_UI.SCANmainMap.DrawWindow (Int32 id)
    SCANsat.SCAN_Platform.SCAN_MBW.DrawWindowInternal (Int32 id)
    UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
    UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)
```

Also accompanied by:

```
Texture '' has no data
```

Since SCANsat is trying to draw the GUI, it's called all the time for 30 seconds or so before the game finally decides to crash entirely.

**Comment by DMagic1** [comment]
I need full log files for this.

**Comment by ThenTech** [comment]
The log files on DropBox: https://www.dropbox.com/s/sulsmj869skootw/%5BSCANsat%5D%20Nullref%20log.rar?dl=0

(There are also errors from ActiveTextureManagement, but I didn't update it yet for 1.0.2 and I don't think it causes the SCANsat error; I will test it again though.)

Edit: It seems it actually was caused by ATM, SCANsat tried to load its icons, but due the older ATM version, the compressed icons weren't there.

**Comment by DMagic1** [comment]
Yes, it looks like there were lots of icon loading errors. ATM just loves to cause theses kinds of problems...
