### ISSUE TITLE
Exception spam

### ISSUE THREAD

**Issue by ghost** [KSPModStewards/SCANsat#155]
After i enter any vessel and wait a while scansat starts spaming exceptions (NullReferenceException: Object reference not set to an instance of an object)

Here is logfile: https://dl.dropboxusercontent.com/u/100811464/output_log.txt
Spam starts from line 49732

I tried removing all scansat data and reinstalling SCANsat,didnt help.

**Comment by DMagic1** [comment]
It looks like something weird is going on when it tries to load data from Sarnus. I'm not sure why it's having that problem, but there is an error when Kopernicus (I think) is loading the OPM planets: search for  PQSMod_VertexPlanet.OnSetup, it shows up on each scene change.

Can you go to Sarnus, is there anything wrong with the planet?

**Comment by ghost** [comment]
Dont see anything wrong with it.

Well after u said it fails to load i reinstalled OPM and that pointed me to that i had old configs for KittopiaSpace for OPM and that caused these problems.After i removed those, all scansat heightmaps were completed without any exceptions.Thanks for help even tho it wasnt SCANsat issue.
