### ISSUE TITLE
Overlays only showing when zoomed out at max

### ISSUE THREAD

**Issue by Olympic1** [KSPModStewards/SCANsat#159]
I'm playing with Outer Planets Mod and I've scanned the planets 100% with all three scanners. When I activated the overlay map for Ore, it didn't show up. Same for the other resources, biome and terrain overlays.

The overlays only showed up when I zoomed very far out in flight view or if I viewed via map view. This only happens for some custom planets, and none of the stock ones.

Zoomed out just before the overlay shows up:
![Not showing](http://i59.tinypic.com/2njfxvk.jpg)

Zoomed out to max, then overlay shows up:
![Showing](http://i60.tinypic.com/n5pzib.jpg)

**Comment by DMagic1** [comment]
This is the only the flight view you're talking about? That's normal. There is a cutoff somewhere that defines when the resource map is visible in the flight view. It isn't something I have control of or that is different from how stock resource overlays work.

**Comment by Olympic1** [comment]
Yes, I only have to zoom out in flight view, when going into map view it shows up at any distance.

too bad that it is a normal behaviour for overlays

**Comment by DMagic1** [comment]
Yeah, it's a stock thing. I just set the resource texture then let stock KSP handle how to display it.
