### ISSUE TITLE
Scansat causing issues with install

### ISSUE THREAD

**Issue by dmwessel** [KSPModStewards/SCANsat#160]
Even without one of the parts being loaded, I'm seeing the following problems in 1.0.4:

(On surface of Kebin):
Mystery Goo part has no context menu to analyze
Jr Science stock part has no context menu
Crew Report and Get Surface Sample buttons do not appear
Thermometer isn't working either
Landed parts are getting a surface speed report of >100 m/s while standing still

I'm in science mode and don't have access to other parts. Scansat itself doesn't generate any data. I have several other mods installed (TAC LS and several mod parts) so I imagine there's a conflic because this goes away if I remove Scansat.

I have the log saved off if I can send it somewhere.

**Comment by DMagic1** [comment]
Upload the log file to dropbox or some other file sharing service please.

**Comment by dmwessel** [comment]
https://dl.dropboxusercontent.com/u/95002492/KSP.log

**Comment by DMagic1** [comment]
It looks like you have two copies of SCANsat in there. One in the standard GameData/SCANsat location, and one in GameData/MechJeb/SCANsat. That would surely cause plenty of weirdness; the MechJeb copy is out-of-date too.

Get rid of that second copy and see what happens.

**Comment by dmwessel** [comment]
That was it, thanks.
