### ISSUE TITLE
Getting impossible contracts with "stock scanning" disabled

### ISSUE THREAD

**Issue by Gnurfos** [KSPModStewards/SCANsat#164]
I disabled "stock scanning" and "instant scanning". As a result, the M700 survey scanner lost its action button to perform an instant scan. However, I'm still getting contracts for "perform an orbital resource survey of X", which I think need this action (it's not the "fuzzy scan" contracts).

**Comment by DMagic1** [comment]
Yeah, I realized this was going to be an issue, but I'm not sure how best to handle it.

You could always switch off the "disable stock scanning" option (and keep the "instant scan" disabled) and do the stock resource scan. It will only work if your orbit is correct, obviously, but it should complete the contract.

That's not really a good solution though.

I might add something like checking if you have over 90% or so scanned with the M700 then automatically do the stock resource scan. Or maybe just put a button in the resource settings window to accomplish the same.

**Comment by Gnurfos** [comment]
Do you mean it's not possible (or too difficult) to prevent these stock contracts from being proposed ? I think some mods filter contracts, but you might not want such dependencies.

To be honest I find the presence of 2 options ("stock scanning" and "instant scanning") rather confusing. To me, either we use stock, which is instant, or we don't at all. I'd even go as far as saying that if you use SCANsat, you should just use it fully, and not have any option for retaining the stock scanning (if you can disable the contracts, of course).

**Comment by DMagic1** [comment]
There are no stock resource scanning contracts. Those likely come from a Contract Configurator pack. Disabling those would probably be somewhat difficult and maybe a game of whack-a-mole (finding all the offending contracts and updating SCANsat every time a new one is released). CC itself has tools for disabling any of its contracts, which is the much simpler solution.

The two scanning options are fairly simple. One (disable instant scanning) prevents any interaction between SCANsat and stock resource scanning, but doesn't actually affect stock scanning. The other goes a step further and disrupts all stock resource scanning functions where possible.

If SCANsat were a progressive resource scanning mod then it might make sense to force one method over the others, but it isn't, so people have options for how they want resource scanning to work.

**Comment by DMagic1** [comment]
fixed in version 14.4
