### ISSUE TITLE
SCANsat & kopernicus biome functionality

### ISSUE THREAD

**Issue by KillAshley** [KSPModStewards/SCANsat#165]
Kopernicus can group bands of similar color and group them together to create biomes using just scaledSpace textures. However doing so removes SCANsat's ability to detect any biomes at all resulting in a blank grey map. My new pack, Uncharted Lands, uses this technique to reduce memory footprint and increase realism in biome mapping, but nothing can be detected by SCANsat.

It seems kopernicus hard codes biome colors to 0.05 floating points, wheres scansat cannot detect anything if this method is used

**Comment by DMagic1** [comment]
This sounds more like a Kopernicus issue. 

SCANsat doesn't really do anything special to handle biomes, it just checks, the biome map attributes for their color, name, and the total number of attributes per planet: [https://github.com/S-C-A-N/SCANsat/blob/release/SCANsat/SCANutil.cs#L332-L370](https://github.com/S-C-A-N/SCANsat/blob/release/SCANsat/SCANutil.cs#L332-L370).

Maybe if I could see where and how Kopernicus is assigning biomes I might have an idea for why SCANsat is having problems reading them.

**Comment by Olympic1** [comment]
https://github.com/Kopernicus/Kopernicus/blob/master/Kopernicus/Configuration/Properties.cs#L216-L230

**Comment by DMagic1** [comment]
Actually, I'm not completely clear on the problem. 

Do you mean the big map shows only a grey biome map, not the static associated with planets that don't have biomes? 

Is this only for the big map, does it happen on the small map, or the biome overlay? What about the stock biome overlay? Do you have the stock style biome map option turned on in SCANsat, or the standard biome map mode?

Pictures and a more complete description of what's going on would help.

**Comment by KillAshley** [comment]
well for example in my Uncharted Lands pack I use the scaledSpace textures as the biome map and use the colors off the planet itself to create biomes. This works great as Kopernicus groups similar color to a degree so the planets have stable biomes and are able to get science from them.

When i use SCANsat and 100% map out a world, the biome overlay only shows a completely grey map with coordinates available. There is no biomes to see, and mousing over doesn't show any biomes either (again, not the static map, just a blank grey map)

Pictures here;
http://imgur.com/a/T009O

**Comment by DMagic1** [comment]
According to that image your vessel doesn't have an active biome scanner and the current mouse location hasn't been scanned for biomes.

Are you sure you scanned with the biome (multispectral) scanner? 

What does the stock biome overlay show? What are your SCANsat biome settings? It's there anything in the log files while generating the biome map?

**Comment by KillAshley** [comment]
had the wrong ship selected (there are like 20 test ships around most planets :(  ) but yes i scanned with a multi.

I did a quick change around and fresh installed everything all over again and made a new game to test. This time it worked perfectly. Very strange it happened, it was the save I've been using to generate and edit bodies on the fly, so possibly something just bugged out in the files and error-ed out everything.

Ill close this Issue. Sorry but thanks for your time anyway!
