### ISSUE TITLE
[suggestion] Allow .csv exports

### ISSUE THREAD

**Issue by marsfan** [KSPModStewards/SCANsat#169]
The only thing that ScanSat does not have that its ancestor (ISA-Mapsat) had is the ability to export a .csv file. When this was possible many people would use the .csv file with software like quickgrid, or to build awesome 3d models of the planets.

**Comment by DMagic1** [comment]
This is what I have so far: 7cb9de07c22298f2ad7885c96704ae42a41764d9

It basically exports a .csv file with: pixel row, column, longitude, latitude, terrain height. 

I should probably switch the lon and lat to be consistent with the pixel order.

It needs a bit of cleaning up, it could be faster to generate. And it needs to be set to ignore regions of the map that aren't used for non-rectangular projections. But I think it covers what is needed. 

I might also set it to output biome data, and maybe resource data too.

It is dependent on scanning coverage, so you can't just export the map to get complete terrain data (you can get an option to fill in scanning for all of the planets if you compile SCANsat in debug mode).
