### ISSUE TITLE
Missing Texture or Placeholder Texture?

### ISSUE THREAD

**Issue by Aivoh** [KSPModStewards/SCANsat#174]
Load(Model): SCANsat/Parts/MULTI/MULTI
Texture 'SCANsat/Parts/MULTI/MULTI' not found!

Only these two textures are in the folder: MULTI_DIFF.dds & MULTI_NRM.dds

Apologies if I am missing something.

Thanks

**Comment by DMagic1** [comment]
Fixed in 77598f6c51195d5c6efa090865a1b4ba773eab66
