### ISSUE TITLE
Missing .dll file

### ISSUE THREAD

**Issue by Stikkychaos** [KSPModStewards/SCANsat#175]
Your latest release on KSP forum seems to be lacking a scansat.dll file, as well as entire [plugin] folder. that is what i have in when i download it 

http://i.imgur.com/URf4thj.png

that in turn makes the mod inactive.

**Comment by DMagic1** [comment]
Download the package (SCANsat-v14.4.zip) from the [release page here](https://github.com/S-C-A-N/SCANsat/releases/tag/v14.4); not the source code.
