### ISSUE TITLE
Updating contracts

### ISSUE THREAD

**Issue by severedsolo** [KSPModStewards/SCANsat#176]
I've done the contract changes for uniquenessCheck - which branch would you like the PR for?

**Comment by DMagic1** [comment]
This is the working fork: https://github.com/DMagic1/SCANsat

But I usually just manually merge pull requests; the license update is also in that branch.

**Comment by severedsolo** [comment]
That's fine - it's just a quick one line replacement in each contract. The PR is there now - do as you wish with it. 

As an aside, I was totally serious about waiving the right to have the link included. I just put it on the thread in case anyone questioned it down the line.
