### ISSUE TITLE
Inactive Space Center and Menu

### ISSUE THREAD

**Issue by Odin52** [KSPModStewards/SCANsat#179]
Hello. I downloaded this mod but i never got it to work, i downloaded the suggested mods listed on the forum page (module manager and mechjab and toolbar). The game itself loads and doesn't crash, but as soon as i load a savegame, it doesn't let me click on either the rocket, or the plane hangar, The launchpad and runway-menu loads, and i can select vehicles and exit that menu, but as soon and i open the others, like tech tree, its loads, but i can't exit. I click on the "back to space center" button and just goes "gray". In the space center, I can rotate the camera and open game menu, but can't load/save or exit. As soon as i try to get bac kto the main menu, in the Debug menu this goes up in red:
 [Exception]: TypeLoadException: Could not load type 'FinePrint.Utilities.WaypointParameter' from assembly 'SCANsat'.
The only way to exit is Alt+F4. I use 1.0.4 and tried useing 32 and 64bit- version, and even clean install too with only mechjeb, the toolbar and scansat, so there are no other mods to interfere with. 
I have a 6-core AMD, a GTX 660 and 12 gigs of ram so performance isn't the issue. Thank you for any help in advance.

**Comment by DMagic1** [comment]
Are you using SCANsat version 14.3, 14.4 or 14.5? Those do not support KSP 1.0.4 or below. Use 14.2.

**Comment by Odin52** [comment]
Thank you for the fast response. I tried using 14.4 14.5 13.?(probably 4) and i found a 'b5' which is, i guess, beta v5, but not sure. I will try the 14.2 if i can find it. Thank you again, I'm desperate, because SCANsat is a must have.

**Comment by Odin52** [comment]
I've tried it right away, and it's WORKING! Thank you very much.
