### ISSUE TITLE
add anomalies (and other markers) to small map and to zoomed-bigmap

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#18]
- (**DwellerBenthos**) wants to see anomalies on the Small map
- S/he also suggests that anomalies (and other markers in general) show up on the zoomed bigmap.

I am more inclined to think the latter is important. The small map is small. Its utility so far has been so far prescribed by its rendering speed and at-a-glance status of progressing scanning. I can't imagine adding markers is going to help speed, and it will certainly clutter up the at-a-glance utility.

But, we shall see.

**Comment by DMagic1** [comment]
Fixed for zoom map long ago; null for the small map.
