### ISSUE TITLE
Kopernicus compatibility

### ISSUE THREAD

**Issue by DMagic1** [KSPModStewards/SCANsat#180]
Kopernicus' on-demand-loading of some aspects of planets seems to be causing issues with SCANsat map caching and loading in the space center and tracking station. Altimetry maps and slope maps are affected; biome maps do not appear to be.

A few things could use some clarification:
- If this is actually the case
- If there is a method of determining whether the height map is unloaded
  - The PQScontroller doesn't seem to be null, as the terrain height calculation doesn't fail
- If there is a method for forcing the height map to load
- If there is a method for unloading the height map again when I don't need it
- If any of this is friendly for reflection methods

if @ThomasKerman could chime in on this it would help.

The affected SCANsat features could be disabled or altered when Kopernicus is installed, but I would rather not have to do that.

**Comment by StollD** [comment]
Well, we replace the Heightmap Object (MapSO) with a custom implementation. It has Load() and Unload() methods, who are controled through a custom PQS Mod. I guess that you should access them through the mod because otherwise you would have tons of reflection or a hard dependecy to Kopernicus. Here is the code for it: https://github.com/Kopernicus/Kopernicus/blob/master/Kopernicus.OnDemand/PQSMod_OnDemandHandler.cs

**Comment by Ruedii** [comment]
Any progress.  I was planning on making some mods to the stock Kerbol system with Kopernicus but this is a deal breaker for it until it's fixed.

**Comment by DMagic1** [comment]
Good timing.

I started working on a solution; I'm not sure if it will work, and I won't get a chance to test it for a while.

I'm not sure on exactly when Kopernicus.OnDemand is unloading MapSOs, right now I'm just assuming it only loads Kerbin in the Space Center scene, and only loads the current planet in the flight scene. I don't want to try unloading something that Kopernicus wants loaded.

**Comment by StollD** [comment]
It unloads them when the PQS gets deactivated, so your method should work. And even if sth. is unloaded by accident, we have code that hotloads the texture if the game reads it and it isn't there. It's all here https://github.com/Kopernicus/Kopernicus/blob/master/Kopernicus.OnDemand/MapSODemand.cs

**Comment by DMagic1** [comment]
Ok, thanks. I think I've got it working now.

Are the biome maps always loaded? And if so, is this only because of the silly way that the stock biome overlays are generated for every celestial body at the same time?
