### ISSUE TITLE
Configuration for which window type is opened by toolbar button

### ISSUE THREAD

**Issue by jd284** [KSPModStewards/SCANsat#195]
The button always opens the small map window. This is never what I actually want, in 90% of the cases I want to open the zoom window centered on the current vessel, in the others I want the big map.

So to get the zoom window, I need to (1) click the toolbar button, (2) click on its "big map" button, and (3) click to zoom on the vessel.

Please make it configurable which window is opened by the button. Or at the very least allow opening the zoom window from the small map.

Alternatively (or in addition), just make it open the zoom window when the button is clicked with the right mouse button, if this is possible.

**Comment by DMagic1** [comment]
If you want better toolbar options I suggest using Blizzy78's Toolbar, it is superior in every way to the stock toolbar and far easier to implement. The stock toolbar is only supported in the most basic way.

Better handling of the zoom map is one of those things that's been on my list forever, but I've never gotten around to it. Currently it is parented to the big map and can't function independent of that. Changing this shouldn't be all that difficult, I'll try to get something into the next version and add a Toolbar icon for opening it, too.

**Comment by DMagic1** [comment]
The new toolbar menu in version 18 should alleviate this.
