### ISSUE TITLE
Small map from right click on 'Big Map' lacks new crp display

### ISSUE THREAD

**Issue by OakTree42** [KSPModStewards/SCANsat#198]
So the small minimap created from right clicking on the 'big map' has the ability to display resources, and it does quite well on the old ones but all the new ones, which do show in the big map, do not show on the smaller map that zooms you in. But the old resources do show there... 

Just a heads up. Not sure how to toggle that on but I suspect it isn't that hard comparatively? Just maybe a line of code somewhere? :D

**Comment by DMagic1** [comment]
This is just a side effect of SCANsat resource scan settings, and adding new resource types. Scan again with the updated scanners and all resources should be visible.
