### ISSUE TITLE
show exit symbol on ground track for active orbit

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#2]
- when?
- which icon number is the exit symbol?
- is this already in the code, but broken?

**Comment by DMagic1** [comment]
As far as I can tell the orbit icon is correct, number 11. I'm guessing that actually displaying it was never implemented.

**Comment by technogeeky** [comment]
I think this is a request for the same thing:
- If you are not yet tired of new features, how about an orbit projection option that shows the orbit where the craft will be taking into account the body's rotation, so you can plan deorbit burns to determine the landing zone in specific locations. (**[KerbMav](http://forum.kerbalspaceprogram.com/threads/55832-PLUGIN-PARTS-0-23-SCANsat-terrain-mapping/page160?p=1161572#post1161572)**)
