### ISSUE TITLE
telemetry tracking

### ISSUE THREAD

**Issue by LexingtonDelta** [KSPModStewards/SCANsat#203]
telemetry data from the sats, as in the path the Sat will follow over 1 or 2 orbits doesnt work anymore atleast on my system, the AP and PA heights DO move around but the blue and orange lines stay at Equator, even on Full polar Orbits. also mines no longer auto refreshing, no other mods installed, KSP 1.0.5 32Bit

**Comment by DMagic1** [comment]
I'm not entirely sure what you're describing; some pictures might help. Do note that the orbit lines won't be displayed in career mode until you have upgraded the tracking station past its initial level.

**Comment by LexingtonDelta** [comment]
![orbits](https://cloud.githubusercontent.com/assets/18104574/14116920/3306442c-f5b0-11e5-84c5-701a2f178bf0.png)

**Comment by DMagic1** [comment]
That looks normal. Do the blue and orange circles not match the orbit? or do they drift away from the orbit somehow?
The blue and orange lines at the equator mark the equatorial crossing points for the next 100 orbits; see the wiki for more info about them.
What do you mean by auto-refreshing? The big map has never done this. You can manually refresh using the circle icon at the top.

**Comment by LexingtonDelta** [comment]
Ok. These make sense then. Is there a way to turn off the equator lines? And the refresh thing might be me remembering an older version lol idk

Sent from Outlook Mobile

On Tue, Mar 29, 2016 at 5:30 PM -0700, "DMagic" notifications@github.com wrote:

That looks normal. Do the blue and orange circles not match the orbit? or do they drift away from the orbit somehow?
The blue and orange lines at the equator mark the equatorial crossing points for the next 100 orbits; see the wiki for more info about them.
What do you mean by auto-refreshing? The big map has never done this. You can manually refresh using the circle icon at the top.

---

**Comment by DMagic1** [comment]
You can't separate the orbit lines from the eq crossing lines, though that has been suggested before.
