### ISSUE TITLE
CKAN SCANsat-pre branch not updated since v9

### ISSUE THREAD

**Issue by RJPercival** [KSPModStewards/SCANsat#205]
It'd be nice if https://github.com/KSP-CKAN/CKAN-meta-dev/tree/SCANsat-pre was updated so that those of us using CKAN could easily install v15 to test with KSP 1.1.

See https://github.com/KSP-CKAN/CKAN-meta-dev/issues/8.

**Comment by DMagic1** [comment]
This one is up to the CKAN people.

I would just assume it not be on CKAN, since I'm really only interested in having enough people try it out to ensure that nothing is badly broken.
