### ISSUE TITLE
ScanSat parts load but have no functionality.

### ISSUE THREAD

**Issue by MeteoVEX** [KSPModStewards/SCANsat#207]
ScanSat parts appear in the VAB and can be attached and launched, but when right-clicked they do nothing. This seems to happen in any game mode. Also, there is "No More Info" displayed with their description in the VAB.

I uninstalled KSP, deleted all files in the KSP program folder, then re-installed KSP from Steam (on Windows 7). I re-downloaded and added only ScanSat and the recommended addons 000_Toolbar and ModuleManager, but experienced the same problem.

I remember ScanSat working for me last year with some other mods installed like RemoteTech and StageRecovery, but it was a while since I played. I hope I'm just missing something simple because ScanSat is possibly my favorite mod. Help! :)

[Screenshot of VAB](http://puu.sh/o5oQR/a85572f92f.png)
[Screenshof of GameData folder.](http://puu.sh/o5oNw/dc2718fe85.png)
[Screenshot of ScanSat folder.](http://puu.sh/o5oOg/2ba368592c.png)

[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/201745/output_log.txt)

**Comment by DMagic1** [comment]
Where did you find that copy of SCANsat? It appears to be at least one and a half years it of date.

The current stable version can be downloaded from Curse, SpaceDock, or the most recent full release on the GitHub releases page: version 14.9. For KSP 1.1 there is SCANsat version 15.1, which can only be found on GitHub.

**Comment by MeteoVEX** [comment]
I THOUGHT was picking it up from http://forum.kerbalspaceprogram.com/index.php?/topic/51073-pluginparts023-scansat-terrain-mapping/

Where the download links direct me to version 14.9 . But, maybe somewhere I got my wires crossed and picked up an old version by accident.

I'm going to try doing this all over again later tonight and double-check the version.

Later tonight I can also try updating to the 1.1 opt-in version and I'll try to find ScanSat 15.1 and see if it works. Thanks

**Comment by DMagic1** [comment]
That thread is, as noted at the top of the first post, discontinued. The thread that it directs you to has links for the current version.

The version you downloaded looks to be v5 or 6.
