### ISSUE TITLE
detect strongly localized biomes and indicate on maps

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#21]
This refers to the fact that our existing biome map has a lot of jagged, rough data where it could look smoother and more general.

So we currently have something like:
![this](http://i.imgur.com/rRsV7oN.png)

Whereas this map has more distinction for the large biome sections?:
![this](http://wiki.kerbalspaceprogram.com/w/images/6/69/MunBiomeMap.png)

I'm not sure what this means exactly. Certainly user-editable color maps would be a good step in this direction.

**Comment by DMagic1** [comment]
I think an expanded range of colors (use two colors further apart in spectrum for the color.lerp) might be preferable to the paint-by-numbers look of the actual biome map colors.

**Comment by DMagic1** [comment]
Redundant to #112
