### ISSUE TITLE
Scansat not working in space

### ISSUE THREAD

**Issue by Larrius243** [KSPModStewards/SCANsat#214]
Hey since updating to 1.1 I did download the updated version of scansat followed the instructions as always but have ran into a issue where you can not do any scanning with them in space even disabled the stock scan but it still will not let me activate the scanners in orbit here is the output file 
[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/237305/output_log.txt)

**Comment by DMagic1** [comment]
It looks like you have a second SCANsat.dll file in your GameData folder. Delete that and see if the issue remains.

The correct location is:
GameData/SCANsat/Plugins/SCANsat.dll

**Comment by Larrius243** [comment]
yup even after doing that still giving me the problem. everything is deployable in the VAB as well but once it is launched an in orbit cant deploy any of them can click an say to start it but it wont do it just sits there

**Comment by DMagic1** [comment]
Do you have log files from after deleting the second copy? The first log file didn't actually have anything beyond the loading process, nothing from the editor or flight scenes.

**Comment by toybcm2** [comment]
I'm also having this same issue since 1.1

here's my output file
[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/239534/output_log.txt)

**Comment by DMagic1** [comment]
It looks like both of you are using Blizzy's Toolbar 1.7.10 and that seems to be causing many problems. 

Update to Toolbar 1.7.11 and see what happens.

**Comment by toybcm2** [comment]
Just updated and it worked, you sir are awesome cx

**Comment by brknglass** [comment]
I had the same problem.  I updated the toolbar but it was still bugged.  I uninstalled the toolbar and everything works perfectly.  Thanks for the support and the awesome mod.

**Comment by fragglea** [comment]
I seem to be having the same issue.  Deployment works fine in the VAB.  As soon as I'm in orbit, nothing.
No deployment, no scanning, nothing..

[KSP.log.txt](https://github.com/S-C-A-N/SCANsat/files/262383/KSP.log.txt)

Got it working......
Same thing.  000_Toolbar was a problem.
Had to delete the whole folder and install it fresh.
(I had just installed it over itself upto that point)
