### ISSUE TITLE
Can't get my scanners to scan

### ISSUE THREAD

**Issue by krishanson** [KSPModStewards/SCANsat#219]
I must be missing something fundamental, and I am a noob with KSP and these great mods, so if I am messing something basic up I wouldn't be surprised.

For whatever reason, I have my SAR sensor in a circularized polar orbit around Kerbin, at 750 km, which according to the doc and context menu on the part should be pretty close to an ideal altitude.  When I bring up the action menu on the sensor, it shows "SCANsat altitude: Ideal".   But the small map shows the "HI" indicator as solid orange and I'm getting no scan result at all.  Any ideas on what I am doing wrong, or what I can try.   Hopefully I'm attaching the correct log file (player.log from my Mac/Steam setup).

I'm really looking forward to mapping out the Kerbal solar system with this mod!

Cheers!
[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/296509/output_log.txt)

**Comment by DMagic1** [comment]
Do the other sensors work? Do you have a save file with the sensor active?

I'm not sure why the sensor wouldn't work, it seems to be registered correctly according to the log file.

**Comment by krishanson** [comment]
I haven't been able to get any of the sensors to work yet.  Here's a [screenshot of the SAR sensor active](http://steamcommunity.com/sharedfiles/filedetails/?id=696150686) and the small map showing the solid orange indicator, despite the sensor context menu saying it is at "ideal" altitude.   So I believe I have things enabled properly.  I'm attaching what I think is the quicksave file (.sfs extension I hope).  If you can think of anything you'd like me to try/test out, just let me know.  Thanks very much!
[quicksave.sfs.zip](https://github.com/S-C-A-N/SCANsat/files/296649/quicksave.sfs.zip)

**Comment by DMagic1** [comment]
That's very strange. I can't see anything wrong.

All of your scanning vessels have the same name? Can you try changing one of them? I don't think that will make any difference (SCANsat doesn't store info by name), but it's worth trying.

Can you also try adjusting the orbit? By all accounts it should work fine at that altitude, but there might be something weird going on.

**Comment by krishanson** [comment]
No joy.  I tried renaming all vessels to have unique names, as well as varying the orbits.  I guess I'll try launching a new probe and see if the problem is repeatable with other scanners.

**Comment by DMagic1** [comment]
I see the problem, the Scan All Celestial Bodies option is unticked in the settings window. 

It looks like the global option is overruling the box for Kerbin, which is activated. I'll see about fixing that, or at least renaming the option to make it more clear that it disables all background scanning.

**Comment by krishanson** [comment]
Awesome, that works fine.   I tried setting a bunch of the different options, but clearly I missed trying that one.   Thanks again, DMagic1.
