### ISSUE TITLE
Enhancement Request: declare some more SCANutil functions as public

### ISSUE THREAD

**Issue by GER-Space** [KSPModStewards/SCANsat#227]
I try to write a KSP-KOS plugin. (new feature for KOS 1.0) to access some of the SCANsat Data within KOS.

It would be great if the following functions where declared public, so I can access them directly.
All declared in SCANutil.cs

getElevation
getBiomeName(CelestialBody body, double lon , double lat)
ResourceOverlay(double lat, double lon, string name, CelestialBody body, bool biomeLock)
slope(double centerElevation, CelestialBody body, double lon, double lat, double offset)

**Comment by DMagic1** [comment]
You want to check if a given area has been scanned then return the desired info?

SCANsat already has public methods for checking to see if a certain location is scanned with a certain scanner type.

The other methods are all just basic KSP stuff. KOS might already have some of them.

The elevation method is the same used by a number of other mods, so you could just copy that verbatim. 
The resource method is also basically what is used by stock. 
The biome method is, I think, more complicated than it needs to be for just getting the biome name, there is a simple method for that in ScienceUtil I think.

Slope is the only tricky one. It is a bit CPU intensive depending on often it is run, and it relies on properly accounting for latitude (the _offset_ argument in the method). Other mods use different methods, most of them rely on the actual terrain being drawn and so only work at low altitudes.

I can make all of those methods public, but it's not likely that I'm going to update before KSP 1.2 comes out. So if you're looking for something faster I would consider using the existing scanning coverage methods and do your own checking for the actual elevation, biome, and resource data.

**Comment by GER-Space** [comment]
Thank you for your response. 

I had the misconception that SCANsat actually stores the data and not only the coverage of the scantype. 

Checking is already public, and the other functions are easy to implement. Is it ok, when I copy the slope function from SCANsat? (with the proper credit of the source)

**Comment by DMagic1** [comment]
Sure. Just note that the slope method isn't something that should be run every frame. SCANsat runs it when you mouse over the map, and, if the instruments window is open, just a few times each second.

Also note that you'll need to properly calculate the offset value, this is used to account for the difference in how much distance is covered by each degree of longitude based on latitude.

See here for how this is handled:
https://github.com/S-C-A-N/SCANsat/blob/release/SCANsat/SCAN_UI/SCANinstrumentUI.cs#L505-L510

**Comment by GER-Space** [comment]
Thank you for your help. I got a first version up and running :-)

[https://www.reddit.com/r/Kos/comments/4tuhq8/kosaddon_scansat/](url)

I will update my plugin within the next few days a bit more, but the most work is done.
