### ISSUE TITLE
Request: use ModuleResource system

### ISSUE THREAD

**Issue by NathanKell** [KSPModStewards/SCANsat#228]
Instead of a hardcoded way of setting up resources and displaying them, please convert to using the ModuleResource system (i.e. RESOURCE node(s) in the MODULE, and using PrintModuleResource to display them in a standardized manner).

This will considerably aid in flexibility, bring the resource display in the editor tooltips in line with all other parts, and (hi!) allow me to report electricity draw in watts.

**Comment by Ruedii** [comment]
Additionally, there should be a second config file method to tell it where to look from any terrain mappable asset, just in case the autodetect doesn't work, or someone wants to make a mod utilizing additional asset sets.

It should be able to handle both coordinate lists and image maps.  Schema formats currently used by most mods should be considered, such as those used by Kerbal Konstructs, waypoint manager, community contract configurator and Mechjeb.  

Map formats should include those used by Environmental Visual Enchancements, Various resource mods, and Kopurnicus. 

Adding imput/output configs for creating and reading variables from RasterProp, if present might also be useful.

This brings a point, maybe we should have a Community Map, Texture and Coordinate Integrator plugin to handle these types of formats as well as texture maps.  Maybe something you and Sarbain could work on, NathanKell?

**Comment by DMagic1** [comment]
@NathanKell 

Sure. When adding the RESOURCE node do I just manually create a new ModuleResource and use Load() with the config node? Then use its values in the SCANsat fixedUpdate method?

@Ruedii 

I'm not quite sure what all of that means. SCANsat doesn't load any data from external sources. The elevation and slope data comes directly from the PQS, which is slow, but the height maps don't represent the final terrain and are too low resolution. The same for the biome map textures and for the stock resource system. Kopernicus planets can be read the same as stock planets.

Other resource systems are either deprecated (Regolith and ORS) or way too much trouble to integrate (Kethane).

Anomalies could be hard coded, to avoid detecting PQSCity objects from mods, but I've never been really sure if that is actually a good idea.

**Comment by NathanKell** [comment]
@DMagic1 yeah you can look at how, say, ModuleSAS handles them (ILspy or whatever; this ain't the forum, I can say that). You check for "RESOURCE" in the load node, and load each one into the resourcesList. Then in your fixedupdate you iterate through each, pulling rate out; and you display them prettily using stock code in GetInfo.

@Ruedii that sounds...rather unrelated to this request, to the extent I understand what you're talking about. Can you maybe make a new issue and try to clarify what you're asking?

**Comment by DMagic1** [comment]
Added in 16.4:

c104929c24c8b6d363bb68072b64981cc11f67cf and 314c14965e49770be0e941fb2a6b587ae29c43b2

**Comment by NathanKell** [comment]
Thanks! :)
