### ISSUE TITLE
Sensors don't work with time warp properly

### ISSUE THREAD

**Issue by Dominik100198** [KSPModStewards/SCANsat#231]
In former times (long ago but already ksp build 1.1.X) the first 2 Sensors (low-res and biome) worked fine.
Without time warp everything is still ok. 
Depending on the warp speed they (low-res, biome, hi-res) are working properly (x1000 warp speed) or not at all (warp speed (higher or) lower than x1000).

my ksp build is 1.1.3 

the mods i am using
![ksp mods](https://cloud.githubusercontent.com/assets/20957110/17572709/44b9b306-5f56-11e6-9fef-13a3847d73b5.PNG)

picture of the issue
![20160810230445_1](https://cloud.githubusercontent.com/assets/20957110/17571177/6408dc16-5f4f-11e6-89cb-997e991ce8b8.jpg)
lastly my x64 output log
[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/412210/output_log.txt)

What am i doing wrong?

Many thanks in advance!

**Comment by DMagic1** [comment]
Check the new version - 16.5, it should fix the problem.

**Comment by Dominik100198** [comment]
Everything is working again. :+1: 
Thank you very much!
