### ISSUE TITLE
SCANUtil.unregisterSensorExternal() don't work anymore

### ISSUE THREAD

**Issue by ShotgunNinja** [KSPModStewards/SCANsat#234]
Somewhere between 16.3 and 16.5 the function stopped working. It return true, but no sensors are unregistered. Calling `SCANcontroller.controller.unregisterSensor` directly (always using reflection) instead work flawlessly. So the problem, for how unlikely it seem, has to be in the function `unregisterSensorExternal`, after the things that can return false (because the function return true) and before its own call to `controller.unregisterSensor` (that work flawless instead). This leave us only this line:

```
int sensor = prefab.Fields.GetValue<int>("sensorType");
```

that is obtaining the field _sensorType_ from the part prefab, and not the module 'prototype' in the part prefab. This in turn probably return 0 and then all the masks for sensor type fail, leading to no sensor being unregistered. The same apply for `registerSensorExternal` as well.

Cheers and keep up the good work.

**Comment by DMagic1** [comment]
Can you try out this version to see if it works?

https://www.dropbox.com/s/8vrbvwqmvib5qwn/SCANsat-v16.6.zip?dl=0

It takes the values directly from the part prefab's modules: f71ebf10db04715bbc83cc8bc15e9c2f2cf18154

If you can confirm everything is fine I'll update.

**Comment by ShotgunNinja** [comment]
Tested, working 100%.
Thanks a lot!

**Comment by DMagic1** [comment]
Fixed in version 16.6
