### ISSUE TITLE
fix zoom box being wonky at poles (ground track)

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#24]
I don't know what wonky means, in this case.

Currently, ground track must mean the dots you see when the Orbit icon is selected.

Perhaps this was a bug which was fixed by our clamping of latitude and longitude, where scanners would scan the opposite pole if the FOV was high enough and the scanner was in a polar orbit.

This merits investigation for that alone.

This was in TODO.txt under 'mine', which I assume to mean damny.

**Comment by DMagic1** [comment]
Fixed in version 6 I think...
