### ISSUE TITLE
Map Width not being accepted

### ISSUE THREAD

**Issue by harryyoung** [KSPModStewards/SCANsat#240]
The map Width Setting is not being accepted or applied to an export.
I tried entering 1920 and hit 'Set', but nothing happened, not even a console output.
I'd really like to export maps larger than 720x360

**Comment by DMagic1** [comment]
Is this in either the Space Center or Tracking Station scene? The map size is fixed in those scenes.

In the flight scene the map resize seems to be working find.

**Comment by harryyoung** [comment]
i'm not talking about rezising the ingame map. that works as intended for me as well. I'm talking about the export width in the settings panel.

**Comment by DMagic1** [comment]
So am I, the Set Width function only works in the flight scene. And the export function just directly exports the map texture, the size can be set in the settings menu or by dragging the resize handle.

I should remove the Set Width function from the settings menu outside of the flight scene to avoid confusion.

**Comment by harryyoung** [comment]
ah! Yeah. Once it is clear that this only works from flight this also works fine. I think this makes it more a case of insufficient documentation. Given that it was listed as an export setting I was assuming that it would overwrite the size of the ingame map for export, so any map exported would have this side length. Instead it just sets he width of the flight scene map.

**Comment by DMagic1** [comment]
I removed the input field from the space center and tracking station scenes. Now it only appears when it can be used.

**Comment by harryyoung** [comment]
Good, That will avoid futher confusion. Thanks
