### ISSUE TITLE
Analyze data button does not work

### ISSUE THREAD

**Issue by demib72** [KSPModStewards/SCANsat#245]
[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/531650/output_log.txt)

I added the latest version of SCANsat today. Considering the post chaos of 1.2, I have not been adding mods as they get updated. But I am getting this exception ever since I added this mod. Noticed something about multiple sciencedefs.cfg might be the cause. But I looked into the ones I have within the game data folder and did not see any duplication of the SCANsatAltimetryLoRes ID. I do not know if that last bit of information is useful.

> [SCANsat] start: live
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [SCANsat] using animation #1 out of 1 animations named 'Collapse_Antenna'
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [SCANsat] sensorType: 1 fov: 5 min_alt: 5000 max_alt: 500000 best_alt: 5000
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> Module ModuleScienceExperiment threw during OnStart: System.ArgumentException: An element with the same key already exists in the dictionary.
>   at System.Collections.Generic.Dictionary`2[System.String,ScienceExperiment].Add (System.String key, .ScienceExperiment value) [0x00000] in <filename unknown>:0 
>   at ResearchAndDevelopment.loadExperiments () [0x00000] in <filename unknown>:0 
>   at ResearchAndDevelopment.GetExperiment (System.String experimentID) [0x00000] in <filename unknown>:0 
>   at ModuleScienceExperiment.OnStart (StartState state) [0x00000] in <filename unknown>:0 
>   at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [R&D]: No Experiment definition found with id seismicScan
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [R&D]: No Experiment definition found with id barometerScan
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [R&D]: No Experiment definition found with id gravityScan
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [R&D]: No Experiment definition found with id temperatureScan
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [R&D]: No Experiment definition found with id atmosphereAnalysis
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> 10/16/2016 4:44:54 PM,KerbalAlarmClock,Vessel Change from 'No Vessel' to 'Xiaomi Survey Sat'

Addendum: I downloaded and installed DMagic Science. The above does not show up. But I get this instead (no experiment definition still happening)

> [DMOS] DMagic Orbital Science Version: [v1.3.3] Loaded
> 
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> [DM] Whoops. Something really wrong happened here, a duplicate science experiment definition may be present somewhere; stopping this contract experiment from loading...System.ArgumentException: An element with the same key already exists in the dictionary.
>   at System.Collections.Generic.Dictionary`2[System.String,ScienceExperiment].Add (System.String key, .ScienceExperiment value) [0x00000] in <filename unknown>:0 
>   at ResearchAndDevelopment.loadExperiments () [0x00000] in <filename unknown>:0 
>   at ResearchAndDevelopment.GetExperiment (System.String experimentID) [0x00000] in <filename unknown>:0 
>   at DMagic.DMConfigLoader.configLoad () [0x00000] in <filename unknown>:0 

Updated log: [output_log2.txt](https://github.com/S-C-A-N/SCANsat/files/531787/output_log2.txt)

**Comment by DMagic1** [comment]
I think this looks like the problem:

```
    Line 6121: Config(EXPERIMENT_DEFINITION) DockingCam/ScienceDef/EXPERIMENT_DEFINITION

    Line 6121: Config(EXPERIMENT_DEFINITION) DockingCam/ScienceDef/EXPERIMENT_DEFINITION

    Line 6254: Config(EXPERIMENT_DEFINITION) OLDD/DockingCam/ScienceDef/EXPERIMENT_DEFINITION

    Line 6254: Config(EXPERIMENT_DEFINITION) OLDD/DockingCam/ScienceDef/EXPERIMENT_DEFINITION
```

Two DockingCam installations. Duplicate experiments will screw up all experiments, it's really irritating that Squad hasn't fixed this.

**Comment by demib72** [comment]
Ahhhh, I see. Somehow that completely eluded me. Removed one and it is back to normal. Though I had the two for awhile and experiments were largely ok. Odd they do not have it ignore duplicates. Is that possible programming wise?

**Comment by DMagic1** [comment]
It is easily possible. And it's extremely annoying that they haven't fixed it and the problem persists.
