### ISSUE TITLE
ScanSat not Scanning resources

### ISSUE THREAD

**Issue by Kemorno** [KSPModStewards/SCANsat#250]
**Scansat isnt scanning the any resource for mun. but it is for minmus (didnt try any other celestial body).
so a little recount just to help to know the issue.**
i launched a recon Sat (probe) for minmus with the propose of going to minmus then mun and then kerbin (all polar orbits), it all went well, i went to minmus, made an orbit of around 60Km, and somehow, after i completed the burn, all the resources were instantly shown on the big map (Scansat map) none of them needed several orbits, it was instantly there.
then i went to the mun and made the same polar orbit, of around 60Km, and after several orbits, nothing showed, not even the ore 0% at the bottom of the big map.so i thought, maybe the resource recon only works with 1 celestial body per launch, so i launched the same craft, but this time directly to mun, and still, nothing appeared.and now i have a Duna Recon (already in orbit with total recon, Alt,Biome,Slope,Resource) ready for transfer, but i'm afraid that i will lose my funds by putting that reconsat at duna's orbit.
**did this happened to any one?
is it a known bug?
is there any solution to that?**
if you need screenshot i can handle u some.

**Comment by DMagic1** [comment]
There is an in-game KSPedia entry and a wiki here on GitHub that goes over resource scanning in detail.

**Comment by Kemorno** [comment]
somehow, when i reopened ksp it started scanning. its ood cause i've tried to reopen it a lot of times... but thx
