### ISSUE TITLE
KSP not loading

### ISSUE THREAD

**Issue by kswiorek** [KSPModStewards/SCANsat#252]
with newer versions of scansat than 16.3 ksp doesnt load
there is a constant error: MissingMethodException: Method not found: 'MapView.get_MapIsEnabled'. in the log, it stopps loading when ksp is starting to open parts from other mods, which use scansat (like dmagic imaging platform).
![image](https://cloud.githubusercontent.com/assets/24269539/20749956/d05722c2-b6f4-11e6-8bab-0b9edf147f0b.png)

log:
http://www.mediafire.com/file/7t1far4s1nmbarf/KSP.log
(mediafire, because file is too large)

**Comment by DMagic1** [comment]
You appear to be using a pre-release version of KSP 1.2. If you want to use that version you will have to forego most mods, as there were only a few updated specifically for the pre-release.
