### ISSUE TITLE
overlay maps onto the spherical surface in the KSP map

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#26]
This comes from TODO.txt:
- overlaying the planets in the stock map view with your generated images, showing them as a solid colour if they haven't been mapped? (**pizzaoverhead**)

This was suggested elsewhere, too, so it is a popular feature request. Obviously, Kethane does something somewhat similar to this already, so it clearly musn't be impossible.

But it would be a large duplication of efforts.

My first thought would be to write new **project** and **unproject** functions that wrap the maps to the sphere. After that, though, I don't know yet.

**Comment by technogeeky** [comment]
This was requested by (**[CaptRobau](http://forum.kerbalspaceprogram.com/threads/55832-PLUGIN-PARTS-0-23-SCANsat-terrain-mapping?p=1161430&viewfull=1#post1161430)**) too:

![example](http://i6.minus.com/ibr3bkILyjrhpf.png)

**Comment by DMagic1** [comment]
Added in version 14 #153
