### ISSUE TITLE
Resource and body names not displaying

### ISSUE THREAD

**Issue by latenightgames** [KSPModStewards/SCANsat#263]
Resource and body names do not display (apart from Eve and water) in any of the map drop downs (the full resource list does appear in the planetary overlay controls). However, although the names don't appear, clicking in the appropriate place does bring up the right body or resource.

Community Resource Pack is installed.

[Log file](http://latenightpartnership.com/KSP_log.zip)

![scansat problem](https://cloud.githubusercontent.com/assets/1469955/24026838/b5b0299e-0abb-11e7-928c-5cc03f5e8494.jpg)

**Comment by DMagic1** [comment]
Should be fixed in version 18.
