### ISSUE TITLE
Remember if SCANsat window was open

### ISSUE THREAD

**Issue by RalfJung** [KSPModStewards/SCANsat#267]
Currently, every time a spacecraft is loaded, the SCANsat window opens in the top-left corner. It would be nice if the window could behave more like e.g. Kerbal Engineer, which will remember if the window was open last time. Many missions I do don't need the SCANsat window, and still I have to close it like a dozen times every time because it keeps popping up.

**Comment by DMagic1** [comment]
Should be fixed in version 18. All windows remember their last used position and the big and small maps remember if they were on or off.
