### ISSUE TITLE
Problem with "Celestial Body" button in v17.7.

### ISSUE THREAD

**Issue by OhioBob** [KSPModStewards/SCANsat#282]
Using Galileo's Planet Pack I've been scanning multiple bodies to produce altimeter maps.  But the "Celestial Body" button won't let me scroll down and select bodies beyond the 5 or 6 that are listed when I first click the button.  When I try to scroll down to see additional bodies, the names jitter, but they won't scroll.  I've performed scans of bodies that I have no way of selecting or seeing their maps.

**Comment by OhioBob** [comment]
UPDATE:  I've discovered that the problem isn't that I can't scroll, it's that the moons are not appearing on the list.  Planets appear, moons do not.  Furthermore, the problem doesn't occur in the stock KSP, only in GPP.  Is this a SCANSat problem or a GPP problem?

**Comment by DMagic1** [comment]
Fixed in version 18.1.
