### ISSUE TITLE
KSP Crash with SCANsat when game load

### ISSUE THREAD

**Issue by GhoustREIDER** [KSPModStewards/SCANsat#284]
[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/1071146/output_log.txt)

(Sorry for bad englesh)
When i start KSP, аt end of the game loading, game crashes.
I try delete some mods. KSP start normaly loading just when i delete SCANsat, I dont understend why they crash and how i can fix it. May by you can halp?

**Comment by DMagic1** [comment]
It looks like you are using a version of SCANsat not compatible with KSP 1.3.

Try this one (or the next update that should release later today): https://github.com/S-C-A-N/SCANsat/releases/tag/v17.7x

**Comment by GhoustREIDER** [comment]
Well ... I installed it .. but again the failure..
This is the first time that a mod produces as many crashes in one day..
Apparently, we will have to wait for SCAN to appear ready and compatible with the game version ..
Then I have to wait, when on CKAN appear Compatible with the version of the game SCANsat

oh, if you need help with the translation into Russian - I can help

**Comment by DMagic1** [comment]
The latest version is compatible with KSP 1.3. If it's crashing then there is something wrong that I need to know about.

**Comment by GhoustREIDER** [comment]
And what can it be?
Is it something I did wrong? Or with a mod code something is wrong?
If it helps I can drop the crash report

**Comment by DMagic1** [comment]
Looking at your log file again, I think RPM may also be out of date. The log shows version 28.1, which is for KSP 1.2.2. It's probably worth checking all of your mods to make sure they support KSP 1.3.

**Comment by GhoustREIDER** [comment]
SCAN earned, the game did not crash, apparently some 1.2.2 modes are not compatible with 1.3 .. know what would be compatible ..
But it's still not clear why until without SCAN but with these mods there was crash ...
thanks for the help
