### ISSUE TITLE
Main window does not close and persistent even in the main menu

### ISSUE THREAD

**Issue by NeuralDip** [KSPModStewards/SCANsat#289]
Hi there,
i just installed version 17.6 and this is what happens. All other windows work fine...
![untitled-1](https://user-images.githubusercontent.com/16197250/27386858-b8440d76-569f-11e7-949f-b03828489ee6.jpg)

thanks

**Comment by DMagic1** [comment]
https://github.com/S-C-A-N/SCANsat/releases/tag/v17.8
