### ISSUE TITLE
Windows Defender AV finds Trojan in Scansat.unity.dll

### ISSUE THREAD

**Issue by Nightside101010** [KSPModStewards/SCANsat#298]
Just got this popup regarding a Trojan in the Scansat files called win32/Azden.A!cl

 Is this actually an issue? I've never had a problem with windows defender and .dll files, in fact, I've never had a pop up at all from Defender.

![image](https://user-images.githubusercontent.com/20480557/30916828-2c005250-a34f-11e7-9966-5d0e1a2fa2e5.png)

I've had  version 18.0 of scansat since it was released.

**Comment by DMagic1** [comment]
Well that's odd. I've never heard of that before. Where did you download it from?

There is no code in SCANsat that connects to the internet in any way. About the only interaction it has outside of KSP is to check if some of the configuration files exist before trying to load them.

The code is obviously available online, and it is the same as the released program, this could be verified by decompiling the .dll files.

If you want you can send me the .dll files and I can decompile them to check if something has been added.

**Comment by Nightside101010** [comment]
I typically download through github, otherwise spacedock. 
Thanks for the offer, but I already had Defender remove the file. I'll download fresh and let you know if the issue comes back.
Thanks for the support and Scansat!

EDIT: Scanned fresh download is clean.

**Comment by DMagic1** [comment]
That's good to know. Let me know if it ever pops up again.
