### ISSUE TITLE
add 'are you sure' button to reset map

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#30]
- (**Geschosskopf**) wants there to be an _Are You Sure?_ dialog (or some other safeguard) injected into the reset map process. Presumably to avoid accidentally deleting his precious scan data.

Sounds like a good idea. It is too easy to wipe out your current map.

**Comment by DMagic1** [comment]
Yeah, I would say this almost qualifies as a bug because it's so easy to reset your data.
