### ISSUE TITLE
Supporting for 1.2.* version?

### ISSUE THREAD

**Issue by byaka** [KSPModStewards/SCANsat#306]
Unfortenly KSP 1.3 not ready yet for RSS+RO, so i'm steal use 1.2 version.
But latest versions of your awesome mod craching my game on loading due 'localizator' class issue.
Any chance to solving this problem?

**Comment by DMagic1** [comment]
The latest version for KSP 1.2 is SCANsat 16.11:

https://github.com/S-C-A-N/SCANsat/releases/tag/v16.11

**Comment by byaka** [comment]
Yep, i know. No plans of backporting new feautures?

**Comment by DMagic1** [comment]
Nope.
