### ISSUE TITLE
v18.3 has a significant increase in CPU consumption versus v18.2

### ISSUE THREAD

**Issue by TruePikachu** [KSPModStewards/SCANsat#311]
I had updated SCANsat from v18.2 to v18.3 via CKAN, and eventually noticed a lot of lag every second in even the main space center scene. After temporary disabling of mods that could be culprits (via renaming their DLLs), I eventually discovered that SCANsat was responsible for it; the debug performance graph went from a big peak every second to something more like an EKG. Telling CKAN to install v18.2 afterwards kept pretty much the same EKG-like not-laggy performance.

**Comment by DMagic1** [comment]
What kind of computer is this on? 

I don't notice any effect from the new scanning coverage calculation, but I might need a potato computer option to revert to the old coverage calculation method.

**Comment by TruePikachu** [comment]
A laptop with a dual-core AMD A6-4400M overclocked to 3.2GHz. The fact it's an AMD is likely relevant; the two cores share a single FPU.

It might be possible to cache the new coverage percentage and (on potatos, at least) only calculate it when the old percentage would have increased by 0.1%.

**Comment by eberkain** [comment]
I am seeing the same performance problem.  Completely stock game with only scansat and MM.  I get a microstutter about every second.  Added memgraph to watch garbage collection and its not related to that.    This even occurs in a fresh sandbox game with 0 active vessels.  Very noticeable when holding right click and dragging to make camera movements. 

I'm running on win 10 64bit, i5 2500k 3.3ghz, 16 gb ram, GTX 970 4 gb

I rolled back to 18.2 and the stutter is not present.

**Comment by StewGoin** [comment]
Also seeing the stutters -- they go away if I disable active scanning in the background settings, nothing else seems to help. Problem also goes away if Scansat is uninstalled -- I'll try rolling back to the last rev and see if it persists.

Windows 10, i5 @4.7ghz, 32g ram, gtx 980 TI

Yeah, reverting to the last version made the stutter go away.

**Comment by DMagic1** [comment]
Check v18.4 and see if it helps.

**Comment by StewGoin** [comment]
Much smoother now it seems.

**Comment by TruePikachu** [comment]
Update appears to return performance (at least from the main space center scene without any active scans in the background) to v18.2 standards. I haven't tested with things actually running scans yet, however.

**Comment by DMagic1** [comment]
Closing this, let me know if any other performance problems come up.
