### ISSUE TITLE
Resource not shown on M700

### ISSUE THREAD

**Issue by EoD** [KSPModStewards/SCANsat#314]
It seems that the name of the resource should be shown in the right-click menu, but it currently just shows a button called "Resource" and the player has then guess which resource is currently displayed.
![image](https://user-images.githubusercontent.com/293499/36077108-bfc85ad6-0f66-11e8-840a-3bf48e52e829.png)
![image](https://user-images.githubusercontent.com/293499/36077164-5b6beb06-0f67-11e8-8b58-e48a075b984f.png)

Previously the menu seemed to look like this: https://youtu.be/rLtBUS7cFJ8?t=4m46s
Currently, the menu looks like this: https://youtu.be/gNbLxfqjOfU?t=10m39s

I am using the Community Resource Pack 0.8.0, RemoteTech 1.8.9 and ScanSat 18.4

**Comment by DMagic1** [comment]
As far as I know this is normal and is a stock KSP issue. Until you click on the 'Resource' button it won't show the actual name. And those are stock resource overlays, SCANsat map overlays are not controlled through the M700 menu.

**Comment by EoD** [comment]
@DMagic1 Please do not close bugs before you get a reply from the reporter...

The bug here is about the fact that **pressing to button does not show the name**.

**Comment by DMagic1** [comment]
SCANsat doesn't do anything with that button unless you disable stock scanning. If stock scanning is disabled all of the stock M700 menu buttons will be disabled, otherwise that is a stock KSP button and a stock KSP problem.

**Comment by EoD** [comment]
So, why does the first video actually show the name of the resource? Did you never handle it before?

It sounds a bit odd, that stock KSP has a resource button when they only have one ressource? Or am I missing something here?

**Comment by DMagic1** [comment]
The first video looks like it was made before 1.3. The localization update changed a lot of things related to how text is shown, this is one of them. 

I would consider the behavior a bug (I mean the way it should be working, where it says Resource until you click on the button), it should update the text for that button as soon as the module is started. Looking at it more carefully, I _think_ it is supposed to do that, but there might be an order of operations problem.

But, if the Resource button never changes that sounds like a different bug. It's possible that it could be related to CRP, but I doubt it, as far as I know all of the CRP resources have proper localization setup, even if they aren't all translated.

I'll try to look into it more to see why it might be working wrong.

**Comment by EoD** [comment]
So, you think that is a CRP bug? I just checked and it has the same effect/behaviour (of not updating the button ever) without ScanSat installed.

If not, would you mind reopening the bug then? I think we both agree that it is "unintended" behaviour on someones side.

**Comment by DMagic1** [comment]
I checked again and I still see the Resource button working as expected. I still consider it's expected behavior to be a bug, it should really never just show Resource. But being stuck on Resource sounds like a separate bug.

Either way it doesn't have anything to do with SCANsat. I would try reporting your problem on the official bug tracker (I don't see any existing bug reports about it): https://bugs.kerbalspaceprogram.com

And I will make a report about the working behavior being non-ideal.
