### ISSUE TITLE
SCANsat contracts locking for no reason.

### ISSUE THREAD

**Issue by Dirosrob** [KSPModStewards/SCANsat#315]
![screenshot3](https://user-images.githubusercontent.com/36383037/36078032-3e05b360-0f37-11e8-8f1b-4754a4cf0d04.png)
I have yet to even activate my low res altimetry sensor, but it seems that the contract locks the instant i enter the Mun's SOI with said scanner. As you can see, the unmet requirement is that I have to have scanned less than 70% of the Mun, despite the fact that i have scanned NONE of the Mun. This is fairly upsetting because the biome scans are pretty lucrative. 

The x64 output log in case you need it:
[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/1714806/output_log.txt)

And for further reference, I'd like to post my save game, but I'm not sure how to since github apparently doesn't like the file format.

**Comment by DMagic1** [comment]
It looks like there are some rounding errors making CC think that the scan is less than the minimum requirement, which is 0%.

For now, if you want to fix it, you can open each of the three contract definitions in the GameData/SCANsat/Resources/Contracts folder and change all lines with:

'minCoverage = 0.0' to 'minCoverage = -1.0'.

**Comment by Bornholio** [comment]
Seeing similar with a RP-1 (RP0 Dev install) sometimes i can catch it at the perfect time and grab the mission.

Made a dropbox link to three modified files for this [temp fix](https://www.dropbox.com/s/a5vricx1ydhk8zu/Scansat%20Missions%20Patch.zip?dl=0) had to fix a bit ago 

GameData\SCANsat\Resources\Contracts\Significant.cfg (3 hits)
	Line 85: 			minCoverage	= -1.0
	Line 95: 			minCoverage	= -1.0
	Line 105: 			minCoverage	= -1.0
GameData\SCANsat\Resources\Contracts\Trivial.cfg (1 hit)
	Line 71: 		minCoverage		= -1.0
GameData\SCANsat\Resources\Contracts\Exceptional.cfg (2 hits)
	Line 78: 			minCoverage	= -1.0
	Line 88: 			minCoverage	= -1.0
