### ISSUE TITLE
switch to map around another mainBody to view progress

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#32]
From [reddit](http://www.reddit.com/r/KerbalSpaceProgram/comments/25wpr2/i_just_released_scansat_v60_check_out_all_of_the/chltbnr):
- Is there a way to view the maps for bodies you aren't currently orbiting just to see how they're doing? I currently just switch around to different crafts but if I'm missing something obvious I'd appreciate a pointer! (**Narmotur**)

**Comment by ghost** [comment]
I think this could be directly related to issue https://github.com/S-C-A-N/SCANsat/issues/26
I know on many an occasion I would have liked to view the scansat info from within the Tracking station. For planning missions and such. Also, considering that it is a tracking station having access to scansat info from within it sounds natural. Of course there would have to be a satellite in orbit of the selected body with some kind of scansat part onboard for it to work... but thats just part and parcel :)
