### ISSUE TITLE
Clamp minimum scanning coverage on KSP 1.3 RP-1

### ISSUE THREAD

**Issue by Tidal-Stream** [KSPModStewards/SCANsat#329]
SCANsat contracts are locking because of clamping issues. See #315. It was closed in d600296 but it was never released for KSP 1.3. In addition, there are other bugfixes (like rounding errors) that were not backported to 1.3. Realistic Progression 0/1 is still on 1.3 so the players would benefit from a release for 1.3 with the bugs fixed.

**Comment by DMagic1** [comment]
Old versions of KSP aren't supported and won't receive new updates.
