### ISSUE TITLE
Missing English text for Jool Multispectral analysis

### ISSUE THREAD

**Issue by omeran** [KSPModStewards/SCANsat#335]
When using the Multispectral analysis platform in Jool low orbit I get the message
> Multispectral Analysis from Jool:
> autoLOC_SCANsat_Science_Multi_Jool2

**Comment by DMagic1** [comment]
It looks like there is a type in the ScienceDefs file for that report:
https://github.com/S-C-A-N/SCANsat/blob/release/SCANassets/Resources/ScienceDefs.cfg#L99

It's missing the leading #

It will be fixed in the next update, whenever that is...
