### ISSUE TITLE
SCANtype limit

### ISSUE THREAD

**Issue by tomasbrod** [KSPModStewards/SCANsat#338]
While adding missing resources from Interstellar (kspie), I exceeded the maximum type. 2^30 seems to be the last working. It is ok to have a limit, but something has to be done about this.

I think the fastest workaround is to remove resources that I do not use in my modpack.

**Comment by tomasbrod** [comment]
Another solution would be to allow registering multiple resources with the same type. Usually one part is used to scan multiple resources at once, so it would not matter.

**Comment by DMagic1** [comment]
This is no longer relevant as all resources are handled by a single scanner type. The high resolution resource scan will handle all of them.
