### ISSUE TITLE
Analyze Data: Radar crashes KSP

### ISSUE THREAD

**Issue by tivec** [KSPModStewards/SCANsat#339]
I've got a low res scan sat in polar orbit of Kerbin, and the moment I press "Analyze Data: Radar", the game freezes and I have to force close it. 

The game behaves as if it runs into an infinite loop.

I tried on an install with just SCANsat installed, and I couldn't seem to reproduce it there, but on this particular install it is a 100% reproducible crash for me. I am quite certain it is an interaction error between SCANsat and one or more mods, but as of yet I haven't managed to find which. If there is one that shines in the log, please let me know, but if it is a bug in SCANsat I'd love to help finding it.

I've attached the log here:
[KSP - Log Scansat.log](https://github.com/S-C-A-N/SCANsat/files/3001821/KSP.-.Log.Scansat.log)

The time for the last log message is the exact moment I press "Analyze Data: Radar", there are no log messages after it.

(Also, if anyone know what mod causes the "Launcher here(in write): False" log message, let me know :D)

**Comment by DMagic1** [comment]
Have you tried removing Science Relay? Or maybe Commnet Constellation? There have been reports before of Science Relay causing crashes when used with mods that alter the stock Commnet system. But there has never been anything repeatable or that I can diagnose. It can happen when any kind of science result is generated.

And if you do find out which mode is printing all of that garbage please file an issue with them and tell them not to do that. It is really annoying when a log file just gets filled up with meaningless garbage like that.

**Comment by tivec** [comment]
I'm enjoying CommNet Constellation but so far I haven't *really* used Science Relay. I will make a copy of my current install and try without them respectively. If Commnet Constellation breaks it, it'd be sad but I can't live without my SCANsat <3

**Comment by tivec** [comment]
Ok, checking in after disabling Science Relay - I could now analyze the data and transmit for science points.

**Comment by DMagic1** [comment]
Closing this, as it relates to Science Relay, not SCANsat.
