### ISSUE TITLE
add MechJeb landing and rover reticles to SCANsat

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#34]
MechJeb has a pretty triangular landing reticle, once you have proposed to land in some location on the big map.

The proposal is to add bidirectional support for this in SCANsat and MechJeb, so that:
1. A user could select a landing location from in SCANsat, and then instruct MechJeb to land at that location (thus, allowing them to use the Big Map and/or Zoom Map instead of the KSP main map)
2. The current landing location should be displayed on the Big Map, with a toggle-able button.
3. Do the same thing with the targets for rovers (so, for instance, you could inspect the planned target for a rover and land a vessel there before the rover has reached it).

I should make a feature request in MechJeb and ask sarbian how best to go about this.

**Comment by DuoDex** [comment]
I would absolutely love if even we could mark a landing location in the ScanSat and have it show up in the map screen and focused on the vehicle (maybe a flag that's toggled in Big Map?). It's really annoying to know where all those great anomalies are and not be able to land precisely on them.

**Comment by DMagic1** [comment]
This can possibly be expanded to include [Trajectories](http://forum.kerbalspaceprogram.com/threads/104694) landing site calculations.

A fairly [straightforward API](https://github.com/fat-lobyte/KSPTrajectories/tree/master/TrajectoriesAPI) exists that should allow for this to be handled through reflection.
