### ISSUE TITLE
Missing "Anomaly" word on the small window

### ISSUE THREAD

**Issue by yalov** [KSPModStewards/SCANsat#340]
On the small window there is "?: Monolith01", most likely it should be "Anomaly: Monolith01", but the "Anomaly" word is missing

![1](https://user-images.githubusercontent.com/12796450/56169600-58002780-5fe7-11e9-95e8-beb79457998c.jpg)

**Comment by DMagic1** [comment]
The ? is intentional in the small map. The map can be made very small, so the text in that readout at the bottom is kept as short as possible to avoid running out of space.
