### ISSUE TITLE
BigMap and ZoomMap wont open (ArgumentException)

### ISSUE THREAD

**Issue by randolfE** [KSPModStewards/SCANsat#342]
Hello There,

ScanSat has been running for a while behaving just normal on many Kerbin Explorations.
All of a sudden BigMap and ZoomMap stopped working. I was opening the Bigmap while i was in the SpacenterView then i switched to a vessel orbiting Mun. While on this vessel i wasnt able to view BigMap or ZoomMap anymore. I allready reinstalled ScanSat with no changes in behavior.

I am using the following mods:
Name                            AssemblyVersion
Assembly-CSharp					0.0.0.0
ModuleManager.2.8.1             2.8.1.0
ModuleManager                   3.0.6.0
ModuleManager                   4.0.2.0
SentinelMission                 1.0.0.0
unBlur                          0.5.0.0
MiniAVC                         1.2.0.6
ClickThroughBlocker             0.1.7.1
MiniAVC                         1.2.0.6
aaa_Toolbar                     1.7.19.0
MiniAVC                         1.2.0.6 
ToolbarControl                  0.1.6.20
B9_Aerospace_WingStuff          0.50.0.0
ContractConfigurator            1.0.0.0 
KerbalEngineer                  1.1.5.7 
KerbalEngineer.Unity            1.0.0.0 
MiniAVC                         1.0.3.2 
MiniAVC                         1.2.0.6 
KramaxAutoPilot                 0.3.6.2 
MechJeb2                        2.5.1.0 
DockingPortAlignmentIndicator   1.0.0.0 
DPAI_RPM                        1.0.0.0 
ModuleDockingNodeNamed          1.0.0.0 
SCANsat                         1.8.10.0
SCANmechjeb                     1.8.10.0
SCANsat.Unity                   1.8.10.0
scatterer                       0.0.0.0 
KSPSteamCtrlr                   0.0.1.35
KerbalAlarmClock                3.10.0.0

**One Warning of my Log:**
[WRN 10:07:49.008] Texture resolution is not valid for compression: 'C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\SCANsat\Icons\SCANsat_Map_Icon.png' - consider changing the image's width and height to enable compression

**Clicking on Toolbar Icon:**
[ERR 10:09:49.714] [Toolbar] [ERROR] error while handling click event: SCANsat.BigMap

[EXC 10:09:49.716] ArgumentException: An element with the same key already exists in the dictionary.
	System.Collections.Generic.Dictionary`2[System.Guid,SCANsat.Unity.MapLabelInfo].Add (Guid key, MapLabelInfo value)
	SCANsat.SCAN_Unity.SCAN_UI_BigMap.get_FlagInfoList ()
	SCANsat.Unity.Unity.SCAN_BigMap.SetIcons ()
	SCANsat.Unity.Unity.SCAN_BigMap.setMap (ISCAN_BigMap map)
	SCANsat.SCAN_Unity.SCAN_UI_BigMap.Open ()
	SCANsat.SCAN_Toolbar.SCANtoolbar+<>c.<.ctor>b__6_1 (SCANsat.SCAN_Toolbar.ClickEvent e)
	SCANsat.SCAN_Toolbar.Button.clicked (System.Object realEvent)
	Toolbar.Command.click ()
	UnityEngine.Debug:LogException(Exception)
	Toolbar.Log:log(LogLevel, Exception, String, Object[])
	Toolbar.Log:error(Exception, String, Object[])
	Toolbar.Command:click()
	Toolbar.Button:click()
	Toolbar.Button:drawInToolbar(Rect, Boolean)
	Toolbar.Toolbar:drawButtons()
	Toolbar.Toolbar:draw()
	Toolbar.ToolbarManager:OnGUI()
	
**Clicking on ScansatButton:**

[ERR 10:09:52.986] [Toolbar] [ERROR] error while handling click event: SCANsat.ZoomMap

[EXC 10:09:52.987] ArgumentException: An element with the same key already exists in the dictionary.
	System.Collections.Generic.Dictionary`2[System.Guid,SCANsat.Unity.MapLabelInfo].Add (Guid key, MapLabelInfo value)
	SCANsat.SCAN_Unity.SCAN_UI_ZoomMap.get_FlagInfoList ()
	SCANsat.Unity.Unity.SCAN_ZoomMap.SetIcons ()
	SCANsat.Unity.Unity.SCAN_ZoomMap.setMap (ISCAN_ZoomMap map)
	SCANsat.SCAN_Unity.SCAN_UI_ZoomMap.Open (Boolean v, Double lat, Double lon, SCANsat.SCAN_Map.SCANmap m)
	SCANsat.SCAN_Toolbar.SCANtoolbar+<>c.<.ctor>b__6_4 (SCANsat.SCAN_Toolbar.ClickEvent e)
	SCANsat.SCAN_Toolbar.Button.clicked (System.Object realEvent)
	Toolbar.Command.click ()
	UnityEngine.Debug:LogException(Exception)
	Toolbar.Log:log(LogLevel, Exception, String, Object[])
	Toolbar.Log:error(Exception, String, Object[])
	Toolbar.Command:click()
	Toolbar.Button:click()
	Toolbar.Button:drawInToolbar(Rect, Boolean)
	Toolbar.Toolbar:drawButtons()
	Toolbar.Toolbar:draw()
	Toolbar.ToolbarManager:OnGUI()
	
[EXC 10:10:07.678] ArgumentException: An element with the same key already exists in the dictionary.
	System.Collections.Generic.Dictionary`2[System.Guid,SCANsat.Unity.MapLabelInfo].Add (Guid key, MapLabelInfo value)
	SCANsat.SCAN_Unity.SCAN_UI_BigMap.get_FlagInfoList ()
	SCANsat.Unity.Unity.SCAN_BigMap.SetIcons ()
	SCANsat.Unity.Unity.SCAN_BigMap.setMap (ISCAN_BigMap map)
	SCANsat.SCAN_Unity.SCAN_UI_BigMap.Open ()
	SCANsat.SCAN_Toolbar.SCANappLauncher.set_BigMap (Boolean value)
	SCANsat.Unity.Unity.SCAN_Toolbar.ToggleBigMap (Boolean isOn)
	UnityEngine.Events.InvokableCall`1[System.Boolean].Invoke (Boolean args0)
	UnityEngine.Events.UnityEvent`1[System.Boolean].Invoke (Boolean arg0)
	UnityEngine.UI.Toggle.Set (Boolean value, Boolean sendCallback)
	UnityEngine.UI.Toggle.Set (Boolean value)
	UnityEngine.UI.Toggle.set_isOn (Boolean value)
	UnityEngine.UI.Toggle.InternalToggle ()
	UnityEngine.UI.Toggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
	UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
	UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
	UnityEngine.EventSystems.EventSystem:Update()
	
[EXC 10:10:20.239] ArgumentException: An element with the same key already exists in the dictionary.
	System.Collections.Generic.Dictionary`2[System.Guid,SCANsat.Unity.MapLabelInfo].Add (Guid key, MapLabelInfo value)
	SCANsat.SCAN_Unity.SCAN_UI_BigMap.get_FlagInfoList ()
	SCANsat.Unity.Unity.SCAN_BigMap.SetIcons ()
	SCANsat.Unity.Unity.SCAN_BigMap.setMap (ISCAN_BigMap map)
	SCANsat.SCAN_Unity.SCAN_UI_BigMap.Open ()
	SCANsat.SCAN_Toolbar.SCANappLauncher.set_BigMap (Boolean value)
	SCANsat.Unity.Unity.SCAN_Toolbar.ToggleBigMap (Boolean isOn)
	UnityEngine.Events.InvokableCall`1[System.Boolean].Invoke (Boolean args0)
	UnityEngine.Events.UnityEvent`1[System.Boolean].Invoke (Boolean arg0)
	UnityEngine.UI.Toggle.Set (Boolean value, Boolean sendCallback)
	UnityEngine.UI.Toggle.Set (Boolean value)
	UnityEngine.UI.Toggle.set_isOn (Boolean value)
	UnityEngine.UI.Toggle.InternalToggle ()
	UnityEngine.UI.Toggle.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
	UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
	UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
	UnityEngine.EventSystems.EventSystem:Update()
[ERR 10:10:27.688] Exception handling event Contract.ParameterChange in class SCANcontroller:System.ArgumentException: An element with the same key already exists in the dictionary.
  at System.Collections.Generic.Dictionary`2[System.Guid,SCANsat.Unity.MapLabelInfo].Add (Guid key, MapLabelInfo value) [0x00000] in <filename unknown>:0 
  at SCANsat.SCAN_Unity.SCAN_UI_BigMap.get_FlagInfoList () [0x00000] in <filename unknown>:0 
  at SCANsat.Unity.Unity.SCAN_BigMap.SetIcons () [0x00000] in <filename unknown>:0 
  at SCANsat.Unity.Unity.SCAN_BigMap.RefreshIcons () [0x00000] in <filename unknown>:0 
  at SCANsat.SCAN_Unity.SCAN_UI_BigMap.RefreshIcons () [0x00000] in <filename unknown>:0 
  at SCANsat.SCANcontroller.onParamChange (Contracts.Contract c, Contracts.ContractParameter p) [0x00000] in <filename unknown>:0 
  at EventData`2[Contracts.Contract,Contracts.ContractParameter].Fire (Contracts.Contract data0, Contracts.ContractParameter data1) [0x00000] in <filename unknown>:0 

[EXC 10:10:27.689] ArgumentException: An element with the same key already exists in the dictionary.
	System.Collections.Generic.Dictionary`2[System.Guid,SCANsat.Unity.MapLabelInfo].Add (Guid key, MapLabelInfo value)
	SCANsat.SCAN_Unity.SCAN_UI_BigMap.get_FlagInfoList ()
	SCANsat.Unity.Unity.SCAN_BigMap.SetIcons ()
	SCANsat.Unity.Unity.SCAN_BigMap.RefreshIcons ()
	SCANsat.SCAN_Unity.SCAN_UI_BigMap.RefreshIcons ()
	SCANsat.SCANcontroller.onParamChange (Contracts.Contract c, Contracts.ContractParameter p)
	EventData`2[Contracts.Contract,Contracts.ContractParameter].Fire (Contracts.Contract data0, Contracts.ContractParameter data1)
	UnityEngine.Debug:LogException(Exception)
	EventData`2:Fire(Contract, ContractParameter)
	Contracts.ContractParameter:SetIncomplete()
	FinePrint.Contracts.Parameters.StabilityParameter:OnUpdate()
	Contracts.ContractParameter:Update()
	Contracts.Contract:Update()
	Contracts.ContractSystem:UpdateContracts()
	Contracts.<UpdateDaemon>c__Iterator1:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by randolfE** [comment]
When loading a different campaign all windows open properly.

**Comment by randolfE** [comment]
Currently BigMap and ZoomMap works fine for Kerbin. Only for Mun the Zoom Map wont open. Can you point me in a direction to look for? Tried ressetting the Scancontroller values with no success.

**Comment by DMagic1** [comment]
This should be fixed in version 18.11.
