### ISSUE TITLE
No Scan Sat intruments can be activated on orbit.

### ISSUE THREAD

**Issue by meeware** [KSPModStewards/SCANsat#346]
I've not been able to activate any scan sat instruments on orbit - radars or sensors.

Notably the DMagic instruments cannot undertake scansat survey actions either. 

I don't have the scansat icon in the toolbar.

[output_log.txt](https://github.com/S-C-A-N/SCANsat/files/3397183/output_log.txt)

**Comment by meeware** [comment]
Note I've also deprecated Lizzy's toolbar manager already, but it doesn't seem to help.

**Comment by DMagic1** [comment]
I don't see anything about SCANsat being installed at all in your log file.

Also, it looks like you are on KSP 1.3, so make sure you have the correct version of SCANsat, as nothing beyond SCANsat version 18.5 will work on KSP 1.3.

**Comment by meeware** [comment]
I must have uploaded an incorrect log file. Apologies.

Have killed game and rebuilt.

All good, thanks for checking back.
