### ISSUE TITLE
Contracts not loading in v19 pre-release.

### ISSUE THREAD

**Issue by Nindydar** [KSPModStewards/SCANsat#360]
Contracts are failing to load for me in the newest pre-release version.

Logs: 
https://pastebin.com/L97tjfw7
https://pastebin.com/CUc5qxpq

**Comment by BolderDufta** [comment]
Get the same errors in v19.1 aswell

**Comment by fragtzack** [comment]
These contract issues seems to be a bug with Contract Configurator mod and not Scan Sat

**Comment by DMagic1** [comment]
I can't remember for sure how the different scan types are handled by CC. If they are hard-coded only the SCANsat layer of CC then that will need updating. 

I'll need to do some testing with CC installed to see what's going on.

**Comment by DMagic1** [comment]
This should be fixable through SCANsat. It looks like it's a data type error that can be easily fixed (that and some half-fixed configs that went out with the last version).

**Comment by DMagic1** [comment]
Should be fixed in version 20.
