### ISSUE TITLE
SCANsat flag

### ISSUE THREAD

**Issue by DMagic1** [KSPModStewards/SCANsat#37]
Turn the SCANsat logo into a KSP flag. I'm not sure exactly what format and dimensions it requires, but it should be simple enough.

Do you have a high resolution version of that logo? Even the current version is probably good enough.

**Comment by technogeeky** [comment]
No, I don't have a high resolution version -- but this version was designed to be the right dimensions for a KSP flag so all we should need to do is ... do whatever you do to make flags out of images.

**Comment by DuoDex** [comment]
![garpffb](https://cloud.githubusercontent.com/assets/7771365/3195173/b382a0a2-ed09-11e3-8fbb-97b3137b1b0a.png)

Make a folder called Flags in the plugin folder and put it in. (All I did was convert it to PNG).

**Comment by DMagic1** [comment]
Yep, it works, thanks. I think it probably needs a different background though

![screenshot12](https://cloud.githubusercontent.com/assets/5150421/3195316/38aa54de-ed0d-11e3-974b-2fd9b924c01c.png)

**Comment by DuoDex** [comment]
Redone
![flag with background](https://cloud.githubusercontent.com/assets/7771365/3195411/b991c8fa-ed0f-11e3-8186-0173c54363f1.png)

**Comment by DuoDex** [comment]
I hope this is better.

**Comment by DMagic1** [comment]
It's great, we'll include in the next update. Thanks.
