### ISSUE TITLE
Old parts are still visible in tech tree & editor

### ISSUE THREAD

**Issue by Angel-125** [KSPModStewards/SCANsat#373]
Absolutely LOVE the new parts in v20! While spending science in career mode, I noticed that the old parts (BTDT, MapTraq, MULTI, RADAR, SAR) were still visible in the tech tree. From what I can see, the part configs have TechRequired set to Unresearchable, but I'm using CTT and UnKerballedStart and they might affect SCANSat. 

Regardless, to really soft-deprecate a part, may I suggest adding "TechHidden = true" to the config? I frequently add that to my old part configs to soft-deprecate the part.

**Comment by DMagic1** [comment]
Fixed in 20.1.
