### ISSUE TITLE
In Daylight label is misleading

### ISSUE THREAD

**Issue by calvin-fisher** [KSPModStewards/SCANsat#377]
MS-R Multispectral is shown claiming no daylight while experiencing direct daylight:
![image](https://user-images.githubusercontent.com/1797159/85189091-32b51c00-b271-11ea-8bf8-5b4f3e55c4b6.png)

Shown here claiming daylight while experiencing eclipse:
![image](https://user-images.githubusercontent.com/1797159/85189151-b1aa5480-b271-11ea-8575-ae950a89edac.png)

The property seems to calculate whether the craft is closer to the sun than the orbiting body, rather than whether there is direct sunlight. In a polar orbit, the setting changes between true to false only when passing over the poles.

**Comment by Kerbas-ad-astra** [comment]
The "in daylight" requirement isn't checking whether the probe is in sunlight, but whether the spot on the planet below it is in sunlight.  In your first image, the probe is over the night side of the Mun, and I suppose that in the second image, the Mun is behind the camera and so the probe is over the day side.  (Perhaps the Mun is being eclipsed in that image, which is not checked for.)

**Comment by DMagic1** [comment]
Yes, the daylight check is for the area of the surface being scanned, not the vessel.

The daylight check does not account for eclipses, it is a simple geometry check that can potentially be run hundreds of thousands of times per second, so it must remain as simple as possible.

**Comment by calvin-fisher** [comment]
It sounds like the calculation is doing what it's supposed to. Calling the property `Surface Daylight` instead of `In Daylight` would help clarify the purpose.

**Comment by DMagic1** [comment]
The text in the indicator has been changed to "Surface In Daylight" in version 20.2. That should be clear enough.
