### ISSUE TITLE
Big map does not refresh with new data unless changing to a different celestial body first

### ISSUE THREAD

**Issue by alex-d-boyd** [KSPModStewards/SCANsat#385]
SCANsat Version: 20.2
KSP Version: 1.10.0.2917 (per CKAN)
DLCs: All

**Issue**
The Big Map does not refresh with newly scanned data after loading a new screen

**Repro**
1. Launch a SCANsat equipped craft into Kerbin orbit and begin scanning.
2. Warp for some time to allow data generation
3. Open big map and click the refresh button
4. OBSERVE: No mapping data is drawn
5. Change celestial body in the Big Map window
6. Change celestial body back to Kerbin
7. OBSERVE: Mapping data is now correctly drawn.
8. Switch back to space center
9. Open big map and click the refresh button
10. Warp for some time to allow further data generation
11. Hit refresh button on Big Map
12. OBSERVE: No additional data is drawn
13. Repeat steps 5 ~ 7

Mod list:
- **[x] Science! Continued** `xScienceContinued 5.26`
- **Chatterer** `Chatterer 0.9.99`
- **ClickThrough Blocker** `ClickThroughBlocker 1:0.1.10.6`
- **Distant Object Enhancement Continued** `DistantObject v2.0.0.2`
- **Distant Object Enhancement Continued default config** `DistantObject-default v2.0.0.2`
- **Docking Port Alignment Indicator** `DockingPortAlignmentIndicator 6.9.1`
- **Environmental Visual Enhancements** `EnvironmentalVisualEnhancements 2:EVE-1.8.0-2`
- **Environmental Visual Enhancements - Stock Planet Config files** `EnvironmentalVisualEnhancements-HR 2:EVE-1.2.2-1`
- **Kerbal Alarm Clock** `KerbalAlarmClock v3.13.0.0`
- **Kerbal Changelog** `KerbalChangelog v1.3.0`
- **Kerbal Engineer Redux** `KerbalEngineerRedux 1.1.7.2`
- **KS3P** `KS3P V6.1`
- **Module Manager** `ModuleManager 4.1.4`
- **PlanetShine** `PlanetShine 0.2.6.3`
- **PlanetShine - Default configuration** `PlanetShine-Config-Default 0.2.6.3`
- **Precise Node** `PreciseNode 1.2.11`
- **RCS Build Aid Continued** `RCSBuildAidCont 1:0.10.0`
- **SCANsat** `SCANsat v20.2`
- **TextureReplacer** `TextureReplacer v4.2`
- **Toolbar Controller** `ToolbarController 1:0.1.9.4`
- **Trajectories** `Trajectories v2.3.3`
- **Transfer Window Planner** `TransferWindowPlanner v1.7.2.0`
- **unBlur** `unBlur v0.5.0`
- **Zero MiniAVC** `ZeroMiniAVC 1:1.1.0.1`

**Comment by hemeac** [comment]
I have come across a similar issue with a new career in 1.9.1, but had only one celestial body so not yet able to confirm steps 5-13.
[KSP.zip](https://github.com/S-C-A-N/SCANsat/files/4908468/KSP.zip)

**Comment by Ernesto-Alvarez** [comment]
Can confirm this problem. The big map does not update, but the real time map does. New data is displayed if KSP is shut down and restarted. I am just working on Kerbin so far, so cannot use the same procedure as the original poster.

KSP version is 1.10.0.2917 (linux)

Mod list: 
- Contract Configurator
- Dangit
- Easy Vessel Switch
- FMRS
- Kerbal Engineer Redux
- KIS
- KAS
- kOS
- Surface Lights
- MechJeb 2
- NavBall Docking Alignment Indicator CE
- RCS Build Aid
- Peristent Rotation
- RemoteTech
- ScanSat
- Stage Recovery
- TAC Life Support

(and all dependencies)
All updated last week.

[KSP.log](https://github.com/S-C-A-N/SCANsat/files/4933992/KSP.log)
[persistent.sfs.txt](https://github.com/S-C-A-N/SCANsat/files/4934003/persistent.sfs.txt)

**Comment by Animatical** [comment]
I'm also experiencing this. 
![screenshot3_LI](https://user-images.githubusercontent.com/64507221/87808453-b984f680-c827-11ea-9a52-bb34cf874a6d.jpg)

**Comment by soylent-keen** [comment]
Also experiencing the same issue as above.  

KSP v1.10.1.2939 (WindowsPlayer x64) en-us
ScanSAT v 1.20.2

ModList:

- Easy Vessel Switch
- Kerbal Engineer Redux
- KIS
- KAS
- Surface Lights
- MechJeb 2
- NavBall Docking Alignment Indicator CE
- RCS Build Aid
- ScanSat
- USI LS
- Click through blocker
- toolbar controller
- antenna helper
- augmented reality
- better save load game
- better science lab

**Comment by DMagic1** [comment]
Fixed in 20.3.
