### ISSUE TITLE
changing time warp resolution changes button coloration under data management

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#39]
In particular, if you click:
- High

Then the buttons:

|  |  |
| --- | --- |
| \* Reset map of the Mun | \* Reset resource maps of the Mun |
| \* Reset **all** data | \* Reset **all** resource maps |

turn green.

If you click Medium, then they are all white.

**Comment by DMagic1** [comment]
This one's my fault. I somewhat unintentionally changed those buttons and they end up inheriting the color from the time warp resolution button. 

It's fixed in my latest commits.
