### ISSUE TITLE
missing SCAN Radar altimeter sensor

### ISSUE THREAD

**Issue by lukeypookie111** [KSPModStewards/SCANsat#406]
missing Scan Radar altimeter sensor

I reproduced it by:
new game maxed starting science, buy all nodes in science till basic science
go to vab, search for it and it isnt there, newest version 20.4

![image](https://user-images.githubusercontent.com/69785730/122641206-e2102180-d157-11eb-8700-c38170e84822.png)

![image](https://user-images.githubusercontent.com/69785730/122641226-03710d80-d158-11eb-924c-9c681f4bd56b.png)

**Comment by lukeypookie111** [comment]
when into config,
![image](https://user-images.githubusercontent.com/69785730/122642323-040ca280-d15e-11eb-949b-46d078ec12ce.png)
edited this config and now it is there
![image](https://user-images.githubusercontent.com/69785730/122642332-12f35500-d15e-11eb-8208-31bdd7b8e0c9.png)

**Comment by Ruedii** [comment]
If I recall that is the old sensor kept around not to break old vessels.

It has since been replaced.

**Comment by RWOne** [comment]
Ruedii is correct ....

**Comment by lukeypookie111** [comment]
ok cause scan sat missions wanted that exact one for scanning missions
