### ISSUE TITLE
Add landing "guidance"

### ISSUE THREAD

**Issue by DuoDex** [KSPModStewards/SCANsat#46]
I suggest some form of marking sites in Big Map that will transfer to the map screen and/or staging view. It's just a nice feature to have when looking for those specific anomalies and trying to land in weird spots for science. Maybe a flag marker that can be "moved" in Big Map?

**Comment by technogeeky** [comment]
This is essentially the same feature as #34; just without the MechJeb involvement.

We already discussed using flags in this way. Actually, we even discussed using flags in orbit!

It's something I want to do, and I think generic support for adding/removing a flag that isn't really intended to be viewed by the end-user is a reasonable way to do it.

**Comment by Zyles** [comment]
Please add this. I'd like a hud marker, or map marker or any marker to pinpoint biomes/locations using SCANsat for my other vessels.

**Comment by DMagic1** [comment]
Added along with MechJeb landing guidance in version 12
