### ISSUE TITLE
Release Candiate 2.3

### ISSUE THREAD

**Issue by pjf** [KSPModStewards/SCANsat#50]
Just a little feedback on RC 2.3:
- There are `*_Scanners.cfg` files in the root of the zip. Should these be under `GameData/SCANsat`?
- `GameData/SCANsat/Thumbs.db` can be removed (harmless).
- There are various `.cfg~` files which can be removed (harmless)

I haven't had a chance to test RC2.3 yet, but I hope to on of my the ludicrous 16 flights I have in the next few days. :)

~ pjf

**Comment by technogeeky** [comment]
All three of these are already addressed in my current branch. Though I do not have a correct .gitignore, yet.
- [x] add Thumbs.db to .gitignore
- [x] add .*~ to .gitignore
- [x] verify scanner configs (in currently private branch)
