### ISSUE TITLE
incorporate Anonymous Mod Statistics

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#51]
I vote to include the anonymous mod statistics mod in future releases of SCANsat.

[Mod Thread](http://forum.kerbalspaceprogram.com/threads/81764-ModStatistics-1-0-0-Anonymous-mod-usage-statistics-Now-for-public-distribution!)

[Source](https://github.com/Majiir/ModStatistics)

[Output](http://stats.majiir.net/)

**VOTES**:
- [x] technogeeky
- [x] DMagic

**Comment by DMagic1** [comment]
I was just about to post the same thing. 

It seems that about 90% of our problems come from other mods, so this is probably a good idea.

**Comment by technogeeky** [comment]
The vote (of two) passes. Assigned to next release.

**Comment by Majiir** [comment]
Glad to hear it. Keep your eyes out for 1.0.2, and poke me on IRC as your release is getting closer if it's not out yet. There's a bug or two that could use fixing, and some additional help info for users.

**Comment by Majiir** [comment]
FYI: ModStatistics 1.0.2 is now out.
