### ISSUE TITLE
Buttons overlay on BigMap

### ISSUE THREAD

**Issue by numbersixonline** [KSPModStewards/SCANsat#54]
If u resize bigmap to minimum it block futher modification since the "rectangular" button overlay the "//" button. Setting reset don't reset windows dimensions.

**Comment by DMagic1** [comment]
See the latest release in the [WIP thread](http://forum.kerbalspaceprogram.com/threads/80661-Jun-11-DEV-SCANsat-v7-0rc2-3-Real-Scanning-Real-Science-at-Warp-Speed%21), it fixes this issue.
