### ISSUE TITLE
SCANsat.dll location warning fires incorrectly in Linux

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#56]
I get the SCANsat.dll warning when I start the game, but SCANsat appears to work fine (other than performance degradation that I do not understand yet).

**Comment by DMagic1** [comment]
By itself there is no problem with SCANsat.dll being in the wrong location. But it implies that the toolbar icons are also in the wrong place and may cause issues with RPM. I don't know why it would cause performance problems.

Do you mean you get the warning when SCANsat.dll is installed in the wrong location? Or that you are getting it all of the time? Maybe there is some difference with Linux for how the URL is determined.

**Comment by technogeeky** [comment]
> But it implies that the toolbar icons are also in the wrong place and may cause issues with RPM. 
> OK.
> 
> I don't know why it would cause performance problems.

I knew it was a mistake when I typed it. I didn't mean to link the two (they are unrelated). And the performance problems may just be because of debugging/tracing.

> Do you mean you get the warning when SCANsat.dll is installed in the wrong location? Or that you are getting it all of the time? 

I am getting the error all the time; I have not tested misplacing SCANsat.dll yet.

> Maybe there is some difference with Linux for how the URL is determined.

Perhaps there is -- at the very least, the path delimiter is different. I will debug this one.

**Comment by DMagic1** [comment]
Should be handled by 668966603e50d843d0c0967cc2e654f928a8231d and 5994e3eaa42abc9bff1dc242efadbc8f5edaa3bc and 736995a66ba61da6e00b5f12b1ee59e9395cb1d4
