### ISSUE TITLE
version numbers should follow the same standard in-game and out-of-game

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#57]
Right now, we things like the following out-of-game to represent SCANsat versions:
- **v6.0**
- **v7.0rc1**
- **v7.0rc2.1**
- **v7.0rc2.4**

Presumably the following would be OK too, even though we haven't used it:
- **v7rc2**
- **v7rc2.4**

But in-game, store these values in some other format and in multiple places.

So let's write a function which uniformly converts the internal (assembly) format to these formats.

**Comment by DMagic1** [comment]
As far as I know the informational version can be set to any string since it's not actually used by anything.

The actual assembly version probably shouldn't be touched to prevent any issues with RPM.

**Comment by DMagic1** [comment]
Fixed in f6edbf385d5e5f80d6c051e2a24c8bdee22f2382
