### ISSUE TITLE
map has no texture

### ISSUE THREAD

**Issue by zeratul254** [KSPModStewards/SCANsat#66]
after setting up a few drones to scan kerbin. I time open up the map to see nothing but grey. So i get the drones scanning thinking that will solve the problem.

nope. i can see where they have scanned but its just a different shade of grey. cant see any of the terrain.

**Comment by DMagic1** [comment]
Many more details are needed: Version used, scanners used, are both maps affected, screenshots, log files (KSP/KSP_Data/output_log.txt).

**Comment by zeratul254** [comment]
apparently i cant upload txt only png gif or jpg.
 using the multi spectrum scanner.
 yes bolth maps.
 scansat version 6.1
playing 32 bit kerbal v .24.2
![screenshot0](https://cloud.githubusercontent.com/assets/8280166/3714637/4d97db94-15b4-11e4-84b6-c98e6dd6c51f.png)

**Comment by technogeeky** [comment]
Judging from the screenshot, this is not a bug.
1. You are scanning **BIO** and **ANOM**.
2. You are viewing Altimetry, which is either **HI** or **LO** resolution.

Try clicking the Biome button on the Big Map, or add a RADAR or SAR scanner to your satellites.
