### ISSUE TITLE
Custom additional contracts for SCANsat 

### ISSUE THREAD

**Issue by Ruedii** [KSPModStewards/SCANsat#67]
I really think that SCANsat needs custom contracts added.

These contracts should be as follows:
1. Test a specified SCANSAT model in **location**.  (Other than ground-testing landed at kerbin, this should be determined by the module.  Obviously BTDT should be either flying between 100m and 2000m.  All others should be in their appropriate normal orbital range. )
2. Transmit or recover **SCAN type** from **location**  (obviously, again location should match type, BTDT being either flying or landed, and all others being orbit.)
3. Complete at least 95% Scan of **SCAN type** of **planetary body**  (This might be slightly more difficult to implement, so the other two should be implemented first.)

Since number 1. and 2. force you to place a SCANsat in orbit, I don't think making one of placing a SCANsat satalite in orbit is necessary, but some people may disagree with me.

**technogeeky edited this comment**: to fix formatting that was being parsed as links

**Comment by technogeeky** [comment]
DMagic and I already think it's important to add contracts. However, we both have been doing other things (including fixing bugs) first. Perhaps this is not the best route.

**Comment by DMagic1** [comment]
Fixed in version 14.2

**Comment by Ruedii** [comment]
I like how this issue was resolved.  It was a great idea to use put hooks in (that can be used by other progression-type mods as well) and then use a separate mod package for the contracts.
