### ISSUE TITLE
investigate and add thermal cooldown requirements before first light

### ISSUE THREAD

**Issue by technogeeky** [KSPModStewards/SCANsat#75]
Many satellites require cooling down to a low operating temperature before they can be used, depending on their purpose, orbit, status, and design. In the extreme case, there are satellites like the James Webb Space Telescope (**JWST**) which have extremely long (several month) cooldown period. This is ostensibly because they are operating in the (far) infrared; and, any heat in some of the satellite components will render the results useless.

However, even normal satellites have some components that need to be cooled down. For example, see [this story](http://www.universetoday.com/113866/nasas-carbon-dioxide-greenhouse-gas-observatory-captures-first-light-at-head-of-international-a-train-of-earth-science-satellites/) about the NASA greenhouse gas observatory. It implies that some parts of the satellite need to be cooled to either (-6 *C) or (-153 *C).

SCAN should investigate adding this property to the scanners as appropriate. This would imply precluding satellite operation ('first light') until after the satellite is cooled down to some target temperature.

It might also include using some resource (cryogenic fuel? electricity?) to _keep_ the satellite cool after the initial cooldown.

**Comment by MOARdV** [comment]
From my perspective as a player, this proposal is throwing hurdles in front of a simple gameplay mechanic.  I primarily use SCANsat to generate maps of worlds so I can make an informed decision about where to land.  Forcing me to sit on a satellite for a period of time ("cooldown") before I can start scanning doesn't add much in the way of fun to the mechanic.  I would much prefer that SCANsat does not drift towards a "hardcore realism" approach that some other mods have taken.  I could see it added as an optional enhancement, like the many life support mods, but not as a required mechanic.  Considering the parts already require electricity to run, one can readily hand-wave that the cooling system is incorporated already.

**Comment by timobleeker** [comment]
I agree with @MOARdV. It doesn't seem to add great gameplay value and just add waiting time. And doing anything with waiting doesn't really make sense in a game where you can timewarp anyway.

However I do see gameplay potential for new mechanics that play with scanning performance etc somehow. In stead of having to _wait_ for a satellite to cool down for it do do anything, maybe an additional part or upgrade can increase performance (resolution, range, scope). Eg. a solar screen such as on the James Webb can increase resolution. You can choose to launch a heavier scanner with screen in one go, or launch it later to improve performance. Just a suggestion.

**Comment by pjf** [comment]
Likewise agree with @MOARdV. This would make a great standalone mod, and maximum operating temperature could be set by that mod for various parts, and those could be applied to SCANsat if installed. It would certainly make sense for things like KSPI which already have helium cryostats for telescope operation.

However this doesn't feel right as _part_ of SCANsat. It's complexity the player may not want, and it's tying behaviour to one part when it would make sense for it to apply to parts from other mods (particularly science instruments).
