### ISSUE TITLE
Update ORS and add license

### ISSUE THREAD

**Issue by DMagic1** [KSPModStewards/SCANsat#76]
[ORS has been updated](https://github.com/WaveFunctionP/KSPInterstellar/tree/master/OpenResourceSystem) with a few fixes along with the [newest version of Interstellar](https://github.com/WaveFunctionP/KSPInterstellar/releases). Nothing that SCANsat uses has been changed, but it's better for everyone to be distributing the same version.

I still don't like the idea of including the ORS.dll in the ORS folder, because it's too easily possible for someone to overwrite or delete it which would break SCANsat. 

SCANsat only really uses two ORS methods, so I want to look into assigning these methods through reflection if performance isn't a problem, but for now it's best to use the latest version before updating to v8.

**Comment by technogeeky** [comment]
OK. I'll add it to the list.

Can you take a look at https://github.com/technogeeky/SCANsat/tree/release/SCANdocs/in/shields and tell me if you agree with the wording? Should MM be seen as required? Should anything else?

**Comment by DMagic1** [comment]
it looks ok. MM should probably be "works with", it isn't required for SCANsat by itself and any of the resource mods or RPM already come with it. Kethane doesn't come with MM, but it isn't technically required here, the SCANsat maps can still show resources scanned by the standard Kethane scanners.
