### ISSUE TITLE
SAR Scanner and Career Mode

### ISSUE THREAD

**Issue by KevinCathcart** [KSPModStewards/SCANsat#79]
The SAR Altimetry scanner is documented as unlocking in the Experimental Science tech tree node. That is very unfortunate given that is empty by default and thus undocumented in places like the official wiki. 

Basically unless somebody uses a tech tree rearranging mod, they have no reason to even expect that node's existance. Also without other mods providing parts in that node, the price of 1000 science is basically unreasonable for unlocking a single part. If 0.25 does not include the feature allowing purchasing of individual science parts for cash rather than science, and does not include stock parts in that node, then please consider moving it.

**Comment by DMagic1** [comment]
All parts are probably going to get tech tree and career mode balancing.

[Community Tech Tree](http://forum.kerbalspaceprogram.com/threads/100385) support is also planned.
