### ISSUE TITLE
Parts not working

### ISSUE THREAD

**Issue by swingkid50** [KSPModStewards/SCANsat#80]
I'm having trouble with SCANsat. I've placed the download directly into my Game Data folder, I've unzipped it directly into the Game Data folder, I've moved the .dll files directly to the Game Data folder, I've moved the parts directly to the Parts folder. I've done all of these things independently from eachother and every time I get the same result, the parts show up in the game but they don't do anything when I right click them. They don't work in the VAB or the launch pad. I've downloaded the tool bars and tried older versions and the latest version. I get the same result every time. I even completely uninstalled and reinstalled KSP and then tried downloading SCANsat, same result, every time. What do I need to try next? I really want this mod.

**Comment by DMagic1** [comment]
> I've placed the download directly into my Game Data folder, I've unzipped it directly into the Game Data folder, I've moved the .dll files directly to the Game Data folder, I've moved the parts directly to the Parts folder. 

Don't do any of that. 

Unzip the SCANsat package somewhere other than inside of the KSP folder. Move everything inside of the newly created GameData folder into the KSP/GameData folder.

It should look like this:

```
 Kerbal Space Program/GameData/SCANsat/...
```

Moving files around independently is a guaranteed way to break things.

**Comment by swingkid50** [comment]
I just did that... it works... I've been trying since last night... It was that easy... everything works now... Thank you DMagic1, I appreciate your help.
