### ISSUE TITLE
Bug! No animation or windows KSP 0.25

### ISSUE THREAD

**Issue by m0thm** [KSPModStewards/SCANsat#91]
Even with the very basic setup below (pod and radar only) there is no animation on start/stop scan and none of teh windows open on icon click or selection from icon's drop down menu. Animation does work in VAB. I have have tried v8.0 through to v9.0rc2 and have the same problem. The bellow KSP.log is from an attempt with v8.0 will be more than happy to provide logs for later versions and help with testing.

![scansat](https://cloud.githubusercontent.com/assets/9440812/4820170/c552f330-5f10-11e4-9a88-4898567b7ed4.png)

m0thm.com/KSP/KSP.log.29.10.14

**Comment by DMagic1** [comment]
You have Tarsier Space Tech installed, get rid of it. It is broken in a very bad way, and it affects other addons like this. In this case it is preventing some crucial SCANsat functions from being properly initialized and loaded by KSP, which basically breaks everything.

I am curious to know, however, if you get any similar kind of debug log spam when this happens on v9.0rc2. I tried to shut things down if this kind of error occurs, but it's not always easy to test.

Something like this; if it happens it should show up anytime SCANsat is loaded (Flight scene, space center, tracking station):

```
    [EXC 01:56:02.163] NullReferenceException: Object reference not set to an instance of an object
      SCANsat.SCANui.gui_show ()
      RenderingManager.OnGUI ()
```

**Comment by m0thm** [comment]
Yep that solved it. Got rid of Tarsier and went back up to v9.0rc2 and all is looking good. Thanks for the pointer do give me a shout if you need a hand with anything i have a bit of time on my hands.
