### ISSUE TITLE
Altitude scale makes some maps unreadable

### ISSUE THREAD

**Issue by rychschax** [KSPModStewards/SCANsat#93]
certain bodies with particularly high elevations (such as bop)  are all but unreadable.  the altitude scale only goes up to 8km above sea level.  as a result, almost all of the map is solid white.  in the future would you consider making the min/max values for the map legend adjustable. this would allow us to compensate for the issue I described, and would also allow us to do things like mapping the topography of oceans with greater precision.

**Comment by DMagic1** [comment]
Fixed in latest Dev Release [V9.0rc2](https://github.com/S-C-A-N/SCANsat/releases/tag/v9.0rc2)
