### ISSUE TITLE
Add support for Stock Toolbar

### ISSUE THREAD

**Issue by Climberfx** [KSPModStewards/SCANsat#94]
Add support for Stock Toolbar option.

**Comment by DMagic1** [comment]
After finally looking into this I've figured it out for my [Contracts Window addon](https://github.com/DMagic1/KSP_Contract_Window/tree/dev). I'll probably add some basic support here; only a single app launcher button to open the small map, which can then open the other windows. And a space center/tracking station button to open the KSC map.

The Toolbar support will remain as long as it's available, even if the stock application launcher is turned on. I'll add an option to disable the stock app launcher button in the settings menu.

**Comment by Climberfx** [comment]
Great Dmagic! Cheers! :D
