### ISSUE TITLE
Big map does not display

### ISSUE THREAD

**Issue by GAPDaTsar** [KSPModStewards/SCANsat#99]
I go to open my maps, the small map works just fine.  Yet the big map does not display.  Instead it's this small 200x100 grey box with nothing inside of it.  It should be made bigger and obviously have all the mapping information in it, instead it's all missing.  Also, I don't know how to resize it.  Is there anyway to fix this?  I have Open Resource System and Karbonite integrated with the SCANsat modification.

**Comment by TaloKrafar** [comment]
I'm having the same issue but I don't have any other mods installed that integrate with SCANsat apart from the other DMagic mod, Orbital Sciences. I've tried uninstalling and reinstalling various other mods including the toolbar but no such luck. I'm also having trouble having some of the sats analyze data.

**Comment by pastlifeuknow** [comment]
![screenshot4](https://cloud.githubusercontent.com/assets/8060451/5565039/2862f5f6-8eaf-11e4-8540-8139a2ef8a39.png)

I don't know about GAPDaTsar but if you look in left top corner of this image you can see a small grey rectangle that is the "Big Map" for me. 

I have MKS (all the suggested applications, but not kethane), TacLife Support, mechjeb and Kerbal Engineer.

**Comment by DMagic1** [comment]
What version of SCANsat is this? Based on the lack of version indicator on your small map I'm guessing it is seriously out of date.

Try again with the latest version, and include more information when posting future bug reports (version number, log files, etc...)

**Comment by pastlifeuknow** [comment]
Yup. that was it. I screwed up the update.

**Comment by driconmax** [comment]
I have the same problem... Is there no solution? I have the last version..

**Comment by DMagic1** [comment]
The solution is hinted at the issue tag; need more information...

**Comment by nashvillecortes** [comment]
Having sort of the same issue. used mod for the first time. tested on kerbin . worked awesome for about half an hour.. i was changing the views.. clicked on polar view.. and its just a grey box. i cant change the view back from polar view because the menu was in that window.. and is now gone. have re-installed the mod and still no good.. when i go to the big map.. its just grey. also my scansat icon in the top right is a grey box. not sure if this is on purpose or not.

**Comment by Phalen** [comment]
I just updated to latest of all mods and minimap works but large map does not.  I get 1/4 the window covered with the big map.  If i try to move it the border disapears and the actual map starts showing. I unfortunatly cant edit my options to set for resource scanning on the big map either :(
![2015-04-29_00001](https://cloud.githubusercontent.com/assets/10489873/7404477/3685c7be-eeb1-11e4-8a85-c8507deb2669.jpg)
usi/art/com res pack/firespitter/mechjeb2/regolith/umbra-amt/exppack/ftt/karbonite/karb+/kolonization/srvpack  are the mods i have installed.

**Comment by futrtrubl** [comment]
A mod that doesn't work with 1.0 yet doesn't work with 1.0 yet. Color me surprised.

**Comment by Phalen** [comment]
color me suprised to, I miss read and thought development was heading towards a v1 release.
